### ISSUE TITLE
Is there a way to execute an entire file without moving the cursor?

### ISSUE THREAD

**Issue by michaelb** [michaelb/sniprun#110]
### Discussed in https://github.com/michaelb/sniprun/discussions/109

<div type='discussions-op-text'>

<sup>Originally posted by **uga-rosa** November  5, 2021</sup>
If I use `:%SnipRun`, the cursor will be moved to the beginnnig of the file.</div>

**Comment by michaelb** [comment]
Looks like it's actually normal vim behavior when calling function over a range

(:help :call)

I need to this `call` thing so it doesn't looks like I'll be able to fix

**Comment by MediosZ** [comment]
Hi, I am really hoping that the cursor will stay at where it is when evaluate the whole buffer.
Is it possible to save the position of the cursor before `call` and restore it after that?
There are some neovim apis like `nvim_win_get_cursor` and `nvim_win_set_cursor` which may help.

**Comment by michaelb** [comment]
@MediosZ this has been 'solved' (a plugin cannot really solve a nvim functionality not behabing like the user wants) in #200

**Comment by MediosZ** [comment]
Sorry I didn't find that, that should help a lot.
Thanks for your effort again!
