### ISSUE TITLE
typescript error

### ISSUE THREAD

**Issue by Tus1688** [michaelb/sniprun#114]
**Describe the bug**
First of all, thank you for making this awesome plugin! It makes me feel like I am using electron text editor 😁. Unfortunately, sniprun didn't giving same result as I type `ts-node filename.ts` on terminal

**What do the bug concerns? Sniprun itself, a particular interpreter?**
I don't know who gave bug, but it seems sniprun.

**To Reproduce**
1. Installed snip run using vim-plug
2. Did `:PlugInstall`
3. ./install.sh didn't install correctly (exit code 1)
4. Went to /.vim/plugged/sniprun
5. Did `bash ./install.sh`
6. Succesfully installed sniprun
7. Did `:checkhealth sniprun`
8. Everything went OK
9. Did `sudo npm install -g ts-node typescript`

**Expected behavior**
The expected output should be: 
<img width="152" alt="image" src="https://user-images.githubusercontent.com/76937231/141668954-2bed05c6-ffa3-4431-9ddf-ab3038cbc79f.png">

**Actual behavior**
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/76937231/141668972-ae1605c8-81eb-41b9-847e-fbdb05637223.png">

**Environment:**
- NVIM v0.6.0-dev+560-g1fdbd29d
- MacOS 12.0.1
- rustc 1.56.1 (59eed8a2a 2021-11-01)

Unfortunately, I couldn't resolve this , do you have any clue?

**Comment by michaelb** [comment]
Will try exactly when I get back to my laptop, butmaybe it's just that.

IIRC  typescript is only supported up to bloc level: you can't send to sniprun different lines of code and expect it to have a 'memory' of variables previously sent.
To achieve that TS would need REPL support in sniprun's term, and that is significantly harder to achieve [than bloc level]

How about you try to sniprun of the whole bloc of code (visual selection + :'<,'>SnipRun) ?

**Comment by Tus1688** [comment]
Hi @michaelb ! Thank you for letting me know, I have tried by highlighting all current buffer, and it works! I admitted I was lost about bloc. Though It would be awesome if TS has REPL support, this plugin has save tons of my time. Thank you for your dedication and hard work. Have a nice day 👍

**Comment by michaelb** [comment]
It's true REPL support gets the user experience to another level.

However I won't probably make a TS repl-capable interpeter anytime soon.... I'm spending my time on another project and only providing bug fixes for sniprun. Feel free to open an issue (with a help wanted label) to ask for that feature, linking to here.

For any future contributor, the probably easiest way is to get inspiration from the Mathematica and Python3_fifo interpeters and make another pipe-based system, but maybe typescript has some special quirk (like the R_original interpreter for R) that make it easier.
