### ISSUE TITLE
Terminal customization/management 

### ISSUE THREAD

**Issue by mmazz** [michaelb/sniprun#130]
It will be nice to have a basic customization on the terminal. Things like change the width, desactivate line numbers (if nvim allows it), change the output looks? (like ipython maybe)

Also have some management like clear the terminal.

**Comment by michaelb** [comment]
I don't know about color, but i can (and will soon) make the width configurable

Closing/clearing & removing the line number column is already implemented and documented [here](https://github.com/michaelb/sniprun/blob/master/ressources/display_terminal.md)

**Comment by michaelb** [comment]
fixed by #131 

I'll close this issue for now, but the last item on your bucket list (output looks, I guess coloration?) may not be so simple. feel free to open a new separate, specific issue for this of course.
