### ISSUE TITLE
(no output) when C snippet includes main()

### ISSUE THREAD

**Issue by erwin** [michaelb/sniprun#133]
**Describe the bug**
When I run `:SnipRun` on C segment that includes a `main()` function, I always get "(no output)". Almost seems like C code is embedded into a template that has already defined the `main()` function. I also can't `#include` anything.

The following works fine:
```c
void foo() {
  int a = 1;
  printf("SnipRun Test: %i...\n", a);
}

foo();
```

**What do the bug concerns? Sniprun itself, a particular interpreter?**

When I do the same thing, but add a `main()` function, the code fails.
I get "(no output)" displayed at the bottom of the editor.

```c
void foo() {
  int a = 1;
  printf("SnipRun Test: %i...\n", a);
}

int main() { foo(); }
```

**Expected behavior**
I suppose you're wrapping up the code in a `main()` function by default, otherwise no segment that doesn't include `main()` would be able to run.

I didn't see if there's a template that you're using to define the default C file that you're including, and if there's some way to override it or disable it.

The bigger related issue is how to set `#include...` lines for a C file.

**Screenshots**

### works fine without main

![image](https://user-images.githubusercontent.com/11534217/148041674-00ca8184-fcfd-459b-acfd-5ae60f0a6384.png)

### no output, yet no error either, when main() is used

![image](https://user-images.githubusercontent.com/11534217/148041590-807eed89-dbef-4e4f-934d-b2a79eda8e8e.png)

**Environment:**
 - Neovim version [e.g. v0.6.1]
- OS/distribution: Ubuntu 21.10
- if possible, GLIBC version (output of `ldd --version`)

```
❯ ldd `which nvim`
	linux-vdso.so.1 (0x00007ffd3dbee000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5ddc6fa000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f5ddc6f5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5ddc6f0000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5ddc60c000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5ddc5f2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5ddc3ca000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5ddceb9000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f5ddc3c3000)
```

**Additional context**

```
sniprun: health#sniprun#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.1 (062421dece3315bd6f228ad6d468cba083d0a2d5) , sniprun will try to make good use of that
  - OK: Rust toolchain found
  - OK: sniprun binary found
  - OK: sniprun binary runs correctly
```

**Comment by michaelb** [comment]
Hi, you guessed correctly, I wrap the snippet inside a 

`int main(){ ......}`

I wasn't so sure about not doing that if a main function was found, so I didn't. The 'no output' you observe is a bug from your point of view, but it's what the code is supposed to do now.

Would you like it that I don't wrap the snippet by `int main()...` if the snippet already contains it?


About the #include issue, it's supposed to work (you shouldn't even have to include them in your sniprun' selection), but please open a separate issue where we can better discuss that

**Comment by erwin** [comment]
Thanks for getting back to me so quickly!!!

I think that including `main()` automatically as you're doing is a very smart way to do it by default.

I also think you're correct though about detecting `main(` in the body.

If `main(` is detected, I think you can assume it's a complete example that can bypass the default template.

For my particular use case, I was writing some documentation, and this is a great way to make sure the documentation embedded in the code actually works, without a bunch of copy paste or fairly complicated parsing.
