### ISSUE TITLE
Simplistic C Build Configuration?

### ISSUE THREAD

**Issue by erwin** [michaelb/sniprun#134]
Building even simplistic C programs often requires:

* (`-I`) Include Path to search for .h Header Files
* (`-L`) Library Path to search for .so or .a Shared or Static Libraries
* (`-l`) library names used when linking

We can set the Include Path for gcc externally via `C_INCLUDE_PATH` or `CPLUS_INCLUDE_PATH`.

We can set the Library Path externally via the `LIBRARY_PATH` environment variable.

`make` will automatically pass the `CFLAGS` environment variable to gcc. Since `make` isn't used, maybe `sniprun` could pass CFLAGS to gcc?

I think the minimal solution would be to document and recommend using [direnv](https://direnv.net/) or one of the many autoenv clones to set `CFLAGS`, `LIBRARY_PATH`, `*INCLUDE_PATH`, and to have `sniprun` pass the value of `CFLAGS` to `gcc` the same way `make` does.

I was thinking that a more elaborate solution would be integrating with one of the existing build systems. I actually think this might be the ideal approach, and would ultimately allow people to run anything. Could be a very fun alternate way to run unit tests by just going into the Unit Test file and doing `SnipRun` on the test you want.

By default, you could just have people define a `default` build target, and put the filename as a comment on the first line of the snippet if they need a specialized build target.

If you are interested in the build system integration route, I recommend looking at [xmake](https://xmake.io/#/) since it's mostly written in `Lua`, it should be easier to integrate with neovim. It's cross language, cross platform, and very fast. `xmake` builds: C, C++, Objective-C/C++, Swift, Assembly, Golang, Rust, Dlang, and Cuda. `xmake` also runs really well on Windows, so if you ever wanted to make `sniprun` work on more platforms, it may be helpful.

Meson isn't bad and works well on Linux, but it's unbelievably slow on Windows. Meanwhile `cmake` is unbelievably slow everywhere...

**Is your feature request related to a problem? Please describe.**

I think it's not currently possible to send `-l` library names to the compiler while using `SnipRun`.

**Comment by michaelb** [comment]
Thanks for the precious feedback

> have sniprun pass the value of CFLAGS to gcc

That's quite legitimate and should be easy, i'll work on it

> run unit tests by just going into the Unit Test file and doing SnipRun on the test you want.

Depending on the complexity of that, it may be completely out of reach for sniprun, alas.
Maybe not forever, but running a 'function' implies also detecting calls to other functions within and quickly turns into a LSP spec nightmare....

I'm less interested by a solution that'd work half of the time, and don't have enough time for any LSP based feature, (but maybe plugins that make use of it can run 'unit tests'?) so we'll probably have to do with the CFLAGS only

> If you are interested in the build system integration route

I'm not really.... Because there's not two people that use the same build system with the same configuration, and that I won't be able to translate any of that into xmake (pr any other). Plus that's overkill for running simple snippets, which are the main focus of sniprun, rather than a complete project

**Comment by erwin** [comment]
> I'm not really.... Because there's not two people that use the same build system with the same configuration, and that I won't be able to translate any of that into xmake

I think you're right. Realistically, even if you did go the `xmake` route and miraculously it was a great fit, inevitably you would get requests for to also support every other build system.....

I think a note about the C build support, and recommending use of something like `direnv/autoenv` might be helpful for users, especially since those variables could cause big problems for other anything else you're trying to build...

---

Maybe something like:

When `sniprun` calls `gcc` to build C/C++ files, you can set the following environment variables to facilitate snippet building:

*  (`-I`) Include path to search for `.h` header files = `$C_INCLUDE_PATH` or `$CPLUS_INCLUDE_PATH`
*  (`-L`) Library path to search for `.so` or `.a` shared or static libraries = `$LIBRARY_PATH`
*  (`-l`) library names (like `-lz` for `libz.so`) and other flags used when building = `$CFLAGS`

Instead of storing all these variables centrally in your `.profile` (which would also likely cause problems for other projects), you can store these in your project folder under `.env` and use a tool like [direnv](https://direnv.net/) or [zsh-autoenv](https://github.com/Tarrasch/zsh-autoenv) to initialize these automatically.

If your C snippet doesn't include a `main()` function, the whole snippet will be wrapped inside of a `main()` function.

All of the `#include`s referenced in the entire file will automatically be in each snippet.

**Comment by michaelb** [comment]
Thanks for formalizing that.

It's rather clear now actually, I think I'll be able to work that out quickly

> If your C snippet doesn't include a main() function, the whole snippet will be wrapped inside of a main() function.

Did that yesterday evening, it's on the dev branch, and will be released with the feature currently discussed

> All of the #includes referenced in the entire file will automatically be in each snippet

Works already, the gif on the README can attest of that

**Comment by michaelb** [comment]
Hi!

Some work has been done, and I'd like your opinion

(Everything is on the dev branch for now, 

you can install it by changing the target of your plugin manager to the 'dev' branch and specifying `bash install.sh 1` as post-install script (mind the "1")

This requires installing Rust, so if you can't/won't, it's fine, but you'll have to wait a bit so that I make a new release)

The documentation in doc/C_original.md has been updated to reflect what's possible now

**Comment by erwin** [comment]
I've done some testing on it and I think it may be working.

I haven't been able to verify for certain because I realized that the particular library I was using ([tbox](https://github.com/tboox/tbox/)) actually has more complicated build requirements than I had noticed previously. Even though it uses `gcc` for the build step, it uses `g++` for the link step.

I'll have to put some other more simple examples together. I'll probably chop up some `xlib` or `xcb` stuff I was working on and use it.

One thing that would be very helpful though, is to print the EXACT arguments that `gcc` is receiving as a command line, so you can copy and paste the log onto the command line and get the same output.

For example, for myself, I noticed the build args are showing up as:

```
[00:00:00.060] (7fd20b00b640) INFO   build args are: ["-I", "/home/ryan/.xmake/packages/t/tbox/v1.6.7/d19ef5f257e947d28660e5dc94dc4375/include", "-I", "/usr/include/glib-2.0:/usr/lib/x86_64-linux-gnu/glib-2.0/include:/usr/local/include:/usr/include/cairo:/usr/include/pango-1.0:/usr/include/harfbuzz:/usr/include/gtk-4.0:/usr/include/glib-2.0:/usr/include/gdk-pixbuf-2.0:/usr/include/graphene-1.0:/usr/lib/x86_64-linux-gnu/glib-2.0/include:/usr/lib/x86_64-linux-gnu/graphene-1.0/include:."]
```

Ideally it would be the whole `gcc` command... even with quoting (within reason)

Also, I'm not sure where in the build process the above is being emitted, but if you're passing it all to `gcc` for a one step build/link, then normally I think the `-I/home/ryan/.xmake/packages/t/tbox/v1.6.7/d19ef5f257e947d28660e5dc94dc4375/include` has to go in as one parameter... Again, not sure where in the build process this part is coming from - maybe it's just being emitted later, or maybe there are just more ways to do it...

Assuming it was matching the command line parameters, I think it would look like:

```
build args are: [
  "-I/home/ryan/.xmake/packages/t/tbox/v1.6.7/d19ef5f257e947d28660e5dc94dc4375/include",
  "-I/usr/include/glib-2.0" 
  "-I/usr/lib/x86_64-linux-gnu/glib-2.0/include"
  "-I/usr/local/include"
  "-I/usr/include/cairo"
  "-I/usr/include/pango-1.0"
  "-I/usr/include/harfbuzz"
  "-I/usr/include/gtk-4.0"
  "-I/usr/include/glib-2.0"
  "-I/usr/include/gdk-pixbuf-2.0"
  "-I/usr/include/graphene-1.0"
  "-I/usr/lib/x86_64-linux-gnu/glib-2.0/include"
  "-I/usr/lib/x86_64-linux-gnu/graphene-1.0/include"
  "-I."
]
```

**Comment by michaelb** [comment]
linking with g++ and advanced stuff are quite out of reach for now, but if you can live with it, you can probably hack an argument on `gcc`'s command line, by using the 'compiler' C_original option in your config

(by setting it to "gcc -SomeRandomFlag" for example)

I made some changes to read correctly the colon-separated env variables and log the full emitted command at the same place you already found the previous logs, now available on dev

**Comment by erwin** [comment]
I moved over to a simple xcb screenshot program that I created a few months back and via `sniprun` I still can't get it to run, even though it's working fine on the command line:

```.autoenv.zsh
CFLAGS="-lxcb -lpng"
LIBRARY_PATH="/usr/lib/x86_64-linux-gnu"
C_INCLUDE_PATH="/usr/include/"
```

Note that gcc requires the components of `$CFLAGS` to be split into individual arguments. Also, the flags must come after the file names, at least for me on gcc version 11.2.0.

```
❯ gcc sniprun.c -lxcb -lpng
# builds ./a.out
```
❯ gcc sniprun.c $CFLAGS
/usr/bin/ld: cannot find -lxcb -lpng
collect2: error: ld returned 1 exit status
# build failed
```

The new `gcc` command line in the log is fantastic.
Unfortunately, I do not see arguments from `$CFLAGS` being inserted into the list.

I don't see `-lxcp -lpng` in the argument list:

```
gcc /home/ryan/.cache/sniprun/c_original/main.c -o /home/ryan/.cache/sniprun/c_original/main -I/usr/include/ -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/local/include -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/gtk-4.0 -I/usr/include/glib-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/graphene-1.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/graphene-1.0/include -I.
```

Since `gcc` will always automatically read $C_INCLUDE_PATH from the environment, you might not have to explicitly pass it to gcc, but instead always pass a `-v` so that a user reading the log can see those paths explicitly.

```
❯ mkdir /tmp/SNIPRUN_INCLUDE_TEST
❯ export C_INCLUDE_PATH=/tmp/SNIPRUN_INCLUDE_TEST
❯ gcc -v sniprun.c -lxcb -lpng 2>&1 | grep -C 5 $C_INCLUDE_PATH

GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "/usr/lib/gcc/x86_64-linux-gnu/11/include-fixed"
#include "..." search starts here:
#include <...> search starts here:
 /tmp/SNIPRUN_INCLUDE_TEST
 /usr/lib/gcc/x86_64-linux-gnu/11/include
 /usr/local/include/x86_64-linux-gnu
 /usr/local/include
 /usr/x86_64-linux-gnu/include
 /usr/include/x86_64-linux-gnu
```

Strangely, I am not seeing the `$LIBRARY_PATH` in the `gcc -v` output though.

**Comment by michaelb** [comment]
Thanks for such precise feedback.

I adjusted some things to log even more things (such as the output of the compiler with -v)

```
CLFAGS env var found : -lpng -lpthread
[00:00:00.012] (7fc93c4a6640) INFO   C_INCLUDE_PATH env var found : /home/lib/lib1:/home/lib/lib2
[00:00:00.012] (7fc93c4a6640) INFO   full gcc command emitted:
gcc /home/michaelb/.cache/sniprun/c_original/main.c -o /home/michaelb/.cache/sniprun/c_original/main -v -lpng -lpthread -I/home/lib/lib1 -I/home/lib/lib2

[00:00:00.071] (7fc93c4a6640) INFO   compiler output:

......(gcc -v output, too long to include here)
[00:00:00.073] (7fc93c4a6640) INFO   [RUN] Interpreter return a result

```
(I ran  `C_INCLUDE_PATH=/home/lib/lib1:/home/lib/lib2 CFLAGS="-lpng -lpthread" nvim ../example.c` then sniprun, to make those variables available)

I'm a bit suprised at the absence of CFLAGS there, since it's the only one I parsed from the beginning... (now all the vars are parsed)
Now that too is logged if the environment variables are detected, so we should be able to understand what is going wrong.

> Since gcc will always automatically read $C_INCLUDE_PATH from the environment, you might not have to explicitly pass it to gcc,

the `gcc` command runs in a sub-shell, so I rather adding the `-I /path/` to the gcc command that setting a env var there, more debuggable and less error-prone. It's supposed to be equivalent....

You should be good to go, but I can't be 100% sure :-)
