### ISSUE TITLE
F# support!

### ISSUE THREAD

**Issue by zetashift** [michaelb/sniprun#141]
**Describe the language you want support for (compiler, specificities)**
I'd like an interpreter for F# that uses F# Interactive [and that work with detected filetypes: fs, fsx]...

**Support Level to achieve**
Bloc

**Additional context**
Maybe using https://docs.microsoft.com/en-us/dotnet/fsharp/tools/fsharp-interactive/ will make it easier to write an interpreter?

**Comment by michaelb** [comment]
Hi! 

It's quite doable.... However I recon you'd like to use F#interactive to provide REPL support ? (Meaning, variables will be reusable from one 'sniprun' to another) That's probably a bit more complicated.

I'll look into it, but anything development-heavy will take some time. And I may be a bit prejudiced, but I hope it works OK on linux (my dev platform) and that the F#i has first-class stdout/in support + doc, but both may not be 100% guaranteed....

**Comment by zetashift** [comment]
Hiya thanks for the fast reply! I mentioned FSI (F# Interactive because I thought it would be the fastest way to get Bloc support in. I don't really need fancy stuff. Besides that the NeoVim F# plugin has a "send to FSI" function already: https://github.com/ionide/Ionide-vim#fsieval-expr , but I like the way SnipRun does it a lot, thus my request.

The new dotnet version works very well with Linux, I use it as well as my dev platform, but I'm not entirely sure about the first-class stdout/stdin support. I'll ask around!

**Comment by michaelb** [comment]
_good_ stdout/stdin is most important for REPL capabilities, simple bloc has basically no requirements besides "you can do a print('hello world') in a terminal with it" (which sadly, exclude languages like piet, chef, sonic pi, and more seriously, stuff like html)

Jokes aside, your actually-lower-than-I-thought expectations are good news for both of us, and while I won't commit, I'd say it'll be pretty easy and you can expect bloc-level for F# pretty by... this weekend...maybe?

**Comment by michaelb** [comment]
![Screenshot_81](https://user-images.githubusercontent.com/44144536/152642595-9e87b67c-680c-4800-a170-54b8f7d689ee.png)
is it just me or is fsi really a galactic gas factory ? My PC ain't potato either, I'm afraid a non-REPL interpreter will be painfully slow on the average laptop

**Comment by zetashift** [comment]
I can't seem to find the way to tell `time` to output cpu usage

![image](https://user-images.githubusercontent.com/1857826/152645244-24ab3e4c-dcbd-450f-8797-5ecaf8c836a8.png)

**Comment by michaelb** [comment]
Sorry for the misunderstanding, I meant that it's painfully slow (rather than a resource hog)

However I can see that it's not only me & a strange bug, but that dotnet fsi _really_ that slow. There's still a chance I can make something usable out of that... Time will tell

**Comment by zetashift** [comment]
Ah I see! Yea usually because I start 1 session and keep it open, I don't really notice the slowness.

**Comment by michaelb** [comment]
Ok!
So, bloc-level (non-REPL) is up in the dev branch (specify the `dev` branch to your plugin manager and use `bash ./install.sh 1` as your post-install command). 
However, right now it takes 2-3s each time for the _thing_ to launch, evaluate the line and return, so.... pretty slow


I feared that a little, but yeah, dotnet fsi is a bit capricious about its stdin. This means I can't do a working REPL with what I have now, _but_:

- the structure is right there and the REPL mode would work, should be dotnet fsi shenanigans be taken care of

- documentation in the dev branch, doc/FSharp_fifo.md, can explain what's going wrong if you want to fiddle around and try different fsharp interpreters (i'd appreciate feedback if you find something)

**Comment by michaelb** [comment]
@zetashift 
Ok! 
So, bloc-level (non-REPL) is up in the dev branch (specify the `dev` branch to your plugin manager and use `bash ./install.sh 1` as your post-install command). 
However, right now it takes 2-3s each time for the _thing_ to launch, evaluate the line and return, so.... pretty slow


I feared that a little, but yeah, dotnet fsi is a bit capricious about its stdin. This means I can't do a working REPL with what I have now, _but_:

- the structure is right there and the REPL mode would work, should be dotnet fsi shenanigans be taken care of

- documentation in the dev branch, doc/FSharp_fifo.md, can explain what's going wrong if you want to fiddle around and try different fsharp interpreters (i'd appreciate feedback if you find something)

**Comment by zetashift** [comment]
I'll have a look when I can, thank you very much!

> However, right now it takes 2-3s each time for the thing to launch, evaluate the line and return, so.... pretty slow

Is the launch penalty a one time cost or does it launch everytime a bloc is evaluated?

**Comment by michaelb** [comment]
Every time a bloc is evaluated 😓

**Comment by zetashift** [comment]
Oof, still, I want to thank you again for a stab at it :D
