### ISSUE TITLE
Support Deno for Javascript and Typescript

### ISSUE THREAD

**Issue by lttr** [michaelb/sniprun#142]
**Describe the language you want support for (compiler, specificities)**
It is often better to run Deno rather than Node for smaller scripts and fast prototyping. It supports both JS and TS and it also have more browser like APIs.
https://deno.land/

**Support Level to achieve**
Any support is useful.

**Additional context**
There might be a need to setup permissions for Deno. I usually run my own local scripts with all permisions like

```
deno -A --unstable script.js
```

**Comment by michaelb** [comment]
Nice idea, I'll have a look

**Comment by michaelb** [comment]
Here it is!

Bloc-level + REPL :-)

**Comment by lttr** [comment]
This is great news! Looking forward for 1.3.

**Comment by michaelb** [comment]
Hey! Typo actually, the current release 1.2.1 already has this included!

(Because there's so much of them, new languages support don't count as a 'feature' for semver increments)
