### ISSUE TITLE
E5107 error when evaluating multi line input including single quotes 

### ISSUE THREAD

**Issue by fhill2** [michaelb/sniprun#144]
**Environment:**
- Neovim 0.6.1
- linux/arch
- sniprun commit [8567986b8c14c8fc3e968a773bf2d5b01060b1ad](https://github.com/michaelb/sniprun/commit/8567986b8c14c8fc3e968a773bf2d5b01060b1ad)

**Describe the bug**
As far as i'm aware, single quotes are still only affected. 
Double quotes, backslashes are fixed in #122.

`TempFloatingWindow` is now the only display option that this errors on.

Single line evals don't error, only when evaluating multiple lines of a file.

**To Reproduce**
`init.lua`

```lua
require'sniprun'.setup({
  repl_enable = { "Python3_original" },    
  display = {  
    "TempFloatingWindow",  
  },
})
```
test file:
```py
print('asd')
import sys
print(sys.platform)
```

`~/.cache/sniprun/sniprun.log` 
```
[00:00:00.026] (7efc3f224640) INFO   disaply floating window res = Err(NeovimError(0, "Vim(lua):E5107: Error loading lua [string \":lua\"]:1: unfinished string near '\"asd'"))
```

Happens on Lua_original, Python_original. Haven't tested others.

**Comment by michaelb** [comment]
Hmmm
![Screenshot_82](https://user-images.githubusercontent.com/44144536/153069825-dc313f3f-14d3-480a-8205-89c970cfdcde.png)

I can't reproduce. Be it with vanilla config, my config, or even directly calling the function `lua require('sniprun.display').fw_open(2,30,'ads') ` that supposedly crashes as reported by this error.... 

Also on neovim 0.6.1, Arch-based distro, tested Python3_original and Lua, tested strings within simple quotes and even containing single quotes, I don't know what I'm missing. Could you include the full log file after one problematic sniprun? Maybe something will catch my eye

**Comment by michaelb** [comment]
Looks like the floating display mode incorrectly escape newlines `\n` actually

**Comment by michaelb** [comment]
reopening since I found out nvim-notify had the same issue (not really using this one myself, but I could've checked)

**Comment by fhill2** [comment]
I appreciate the fast fix @michaelb.
I can confirm for the Floating Window view mode, `\n` is now being handled correctly.

**Comment by michaelb** [comment]
You're welcome, in fact I should thank you too for the time you're taking opening these issues
