### ISSUE TITLE
Use the customized interpreter other than provided in the doc?

### ISSUE THREAD

**Issue by milanglacier** [michaelb/sniprun#149]
Is it possible to customize the interpreter I want?
Currently, I want `ptpython` and `radian` as the interpreter for python and R.
I also want `rmd` enabled to use `radian` as the interpreter.

**Comment by michaelb** [comment]
Yep, absolutely!

Mind the difference between a language interpreter (python3, radian....) and sniprun' Interpreter (Python3_fifo, Rust_original)

A list of the latter can be found with `:SnipInfo`

The documentation `:SnipInfo Python3_original` (or whatever sniprun' Interpreter you wish to use) is only an example; you can use anything (except a relative path) in the config field

**Comment by milanglacier** [comment]
> Yep, absolutely!
> 
> Mind the difference between a language interpreter (python3, radian....) and sniprun' Interpreter (Python3_fifo, Rust_original)
> 
> A list of the latter can be found with `:SnipInfo`
> 
> The documentation `:SnipInfo Python3_original` (or whatever sniprun' Interpreter you wish to use) is only an example; you can use anything (except a relative path) in the config field
> 
> I don't exactly know what "rmd enabled" entails

End

Thank you for your quick response. I’ll take a look on how to modify it.

rmd is a plain text notebook for R. It is just another filetype. I.e I want to set interpreter for a new filetype.

**Comment by michaelb** [comment]
> rmd is a plain text notebook for R. It is just another filetype. I.e I want to set interpreter for a new filetype.

The configuration section has an example of using the `use_on_filetypes` config field, which is exactly what you need

**Comment by milanglacier** [comment]
Thank you! I'll look at the doc.
