### ISSUE TITLE
Live mode returns nil when regular SnipRun returns correct output

### ISSUE THREAD

**Issue by yingzhu146** [michaelb/sniprun#155]
**Describe the bug**

I use https://github.com/akavel/up a lot for quick iteration on awk/sed/grep/regex's on standard output. So when I read about live mode, which would allow me to have this AND all neovim goodies right in the editor  I was delighted.
However, it behaves weird in two situations:

1) reading files (yes, I read `    - disable the live mode whenever your code modifies files or invoke system commands.` in `sniprun/ressources/live_mode.md`, but that's what I need for a similar workflow to `up`)
2) working with scripts which contain pre-existing code

I've tried this in python and lua, both same issue

For issue 1)
Here's using regular SnipRun
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/59233975/164993750-00ee5d83-62d5-434f-88e9-ed2351864827.png">
Here's when starting with an __EMTPY__ file and typing the same code with live mode enabled 
<img width="1787" alt="image" src="https://user-images.githubusercontent.com/59233975/164993768-6d1a9369-bbff-4a81-8dd9-920e89df4516.png">
(on the right you can see file exists)

For issue 2)
Here, the red text was in the script before opening, when I then start live mode, that part appears to be ignored.
<img width="831" alt="image" src="https://user-images.githubusercontent.com/59233975/164993803-2f9a53f6-e093-44d0-830e-8081fc67959a.png">
Note: even if I e.g. redefine the variable after starting live mode, it still shows nil

**Environment:**
 - Neovim version `NVIM v0.8.0-dev+1468-gd3121f1e6`
- OS/distribution `OSX 12.3`
- if possible, GLIBC version (output of `ldd --version`)
- Sniprun
```
- -n Version :  v1.2.2

```

Can't tell you how excited I am about live mode to very quickly iterate on python/lua/... regexes and other data parsing (e.g. API request results) et al - would be a game changer!

**Comment by michaelb** [comment]
> reading files

Sniprun has (documented, i believe) trouble with relative paths. That probably...won't change, but maybe I can work on a configuration switch to enable sniprun to work in 'the current directory'

> working with scripts which contain pre-existing code

> Here's when starting with an EMTPY file and typing the same code with live mode enabled

Well, live mode works by running the "current-line-you're-modifying" only. You should probably enable "REPL" (sniprun has several repl-capable interpreters for python and one for lua) so that sniprun remembers the previous lines. That variable shouldn't be _nil_ anymore after that

**Comment by yingzhu146** [comment]
Sorry - finally had time to test this again - it works now without typos in config and the right setup, and using `Python3_original` an full paths (`Python3_fifo` crashed after every second line).

Few things would've made it a bit easier:

1) `SnipInfo` displaying info like `LspInfo`
2)  the logs are very verbose - it was very difficult to realize where what happens
3) Help with relaying a bit more errors - I feel like (pure UX, probably not config'd right) often just nothing happens and I have no idea why - other live mode repls like codi, up will just show syntax errors etc when your code is incomplete yet. As it is, I feel like iteration speed (which is my big selling point for live mode) is still faster to just `:!chmod +x %` and `vsplit  | te %` via keymaps, or use something like https://github.com/jghauser/kitty-runner.nvim since some errors will happen anyways and my shell is at least vocal about it.

Feel free to ignore all, probably just rambling. This can be closed from my end :)

**Comment by michaelb** [comment]
> Feel free to ignore all, probably just rambling. 

One's man rambling is another man's precious feedback, they say

> (Python3_fifo crashed after every second line)

that one is definitely a bug. I'll test

1. Nice idea :-)
2. Yeah, but at the same time, it's not possible to debug every possible bug if they aren't. Those are supposed to be more dev(me)-facing than user-facing, and I can make sense of that unstructured mess easily enough for now.
3. There are several issues here:
    - Live-mode is (for now) limited to a line-by-line basis: I can't make sense of `def f_test():` because it doesn't mean anything on its own. You can, however, make a visual selection and send it to sniprun the usual way, it'll be taken into account by subsequent live mode runs.
    - Errors are way too verbose for virtual-line display, and sumarizing them an impossible task. I could make the thing display a red 'x' or '?' though \*
    - " is still faster to just :!chmod +x % and vsplit | te % ". `:%SnipRun` is basically equivalent then

\* I'll keep that in mind for a future release, maybe not the next one but sometime...
