### ISSUE TITLE
Building from source no longer working

### ISSUE THREAD

**Issue by axrt** [michaelb/sniprun#161]
Hi!
First of all, ENORMOUS thanks for the plugin, use it almost every day, a total
lifesaver!

**Describe the bug**

so, I used to have the binary component built from source with the recommended
`./install.sh 1`, but since sometime ago I noticed that the healthcheck was not
passing, I went on to see what was going on, and it looks like it stopped
building for me, here is a manual attempt with cargo:

```sh
cargo build
...
   Compiling .. blah blah omitted for brevity..
...
error: there is no argument named `v`
  --> src/interpreters/OrgMode_original.rs:51:48
   |
51 |             info!("running separately ranges : {v:?}");
   |                                                ^^^^^

error: there is no argument named `counter`
  --> src/interpreters/OrgMode_original.rs:45:29
   |
45 |             info!("counting {counter} code blocs delimiters");
   |                             ^^^^^^^^^

error: there is no argument named `l`
  --> src/interpreters/OrgMode_original.rs:32:54
   |
32 |             info!("checking code bloc delimiter in : {l}");
   |                                                      ^^^

error: there is no argument named `v`
  --> src/interpreters/GFM_original.rs:56:48
   |
56 |             info!("running separately ranges : {v:?}");
   |                                                ^^^^^

error: there is no argument named `counter`
  --> src/interpreters/GFM_original.rs:50:29
   |
50 |             info!("counting {counter} code blocs delimiters");
   |                             ^^^^^^^^^

error: could not compile `sniprun` due to 5 previous errors
```

Kindly advise? I would be ready and willing to test on a linux and mac if need be, just need some guidance!

**What do the bug concerns? Sniprun itself, a particular interpreter?**

looks like smth is not great with my rust installation, but not sure.

**Environment:**

This is my neovim:

```sh 
NVIM v0.8.0-dev+1623-gc55867b46
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by ec2-user@ip-10-129-1-77.us-west-2.compute.internal
```

ldd:

```sh
ldd (GNU libc) 2.26
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

cargo and rustc from nightly, v 1.55.0

Thank you very much in advance!

**Comment by michaelb** [comment]
Hey! It mostly looks like you have a rust version older than format strings feature (they were introduced in 1.58).

`rustup update stable`  - should your installation be 'standard' - will solve this issue.

I can remove those info! calls, but as (AFAIK) there is no tool to ensure me or some other contributor won't add some again in the future, so i'd rather specify a MSRV in the README and Cargo.toml

**Comment by axrt** [comment]
Thank you the prompt reply, yes, indeed it does compile this time. the only
problem I seem to be having now is that I am stuck with glibc 2.26, and it looks
like we are linking against glibc 2.28 at minimal.. I will see if I can get
around this. Thanks again!

**Comment by michaelb** [comment]
Then I'll see that the next release  is compatible with pre-1.58 Rust :-)

**Comment by axrt** [comment]
I think there is no need to downgrade rust's version tbh, it's more like one of
the crates (I am guessing it's gotta be `libc`) is trying to link against a
`glibc` of a certain minimal version. Let me play with this a bit, and I might
come back with a solution. There has to be a way around without the need for
keeping eye on the legacy-ish users like myself. It looks like the way around
would be to just "me compiles another `glibc` somewhere, me forces `sniprun` to
link against that `glibc`, me creates an FAQ or a pr for the installation
script, you approves, partially - people do not notice, partially, older
glibc-people like myself go on enjoying sniprun with full functionality")

**Comment by axrt** [comment]
ok, @michaelb, I am not sure if you'd accept this solution before I open a pr, so we can discuss first:)
so, I think a way to fix this once and for all is to link against `glibc` statically, this is what I did:

```
RUSTFLAGS="-C target-feature=+crt-static" cargo build --target x86_64-unknown-linux-gnu --release
```

However, this will build in `target/x86_64-unknown-linux-gnu/release`, not where the plugin is looking for the `sniprun` executable. If we then softlink it say, 

```
ln -s <path_to_sniprun_src>/target/x86_64-unknown-linux-gnu/release/sniprun  /<path_to_sniprun_src>/target/release/
```

we will then have the static sniprun that offers this in response to `checkhealth sniprun`

```
        1
         2 sniprun: health#sniprun#check
         3 ========================================================================
         4 ## Installation
         5   - OK: Rust toolchain found
         6   - OK: sniprun binary found
         7   - OK: sniprun binary runs correctly
         8
```

Essentially, my point being is that we might go about this in a way that the gh CI still uses ubuntu 20.smth, compiles with the `RUSTFLAGS` as mentioned above, but pushes the linux target for `x86_64-unknown-linux-gnu` (which I think might be default anyway). Then it is virtually guaranteed that whoever does not use the `1` with the `./install.sh`, but just relies on the script to download `sniprun` for them will end up with a `glibc`-independent binary.

Let me know your thoughts, I can change either the gh job and/or the installation script and open a pr.
Thanks!

**Comment by michaelb** [comment]
This is a great idea, actually. 

My fears would be that the generated binary would be much larger, which isn't the case (5.2MB -> 6.4MB).

Acutally, the install script won't have to be modified, only the release workflow: `.github/workflows/release.yml`, so linking anything anywhere will not be needed.

You're free to open a PR of course, but since a typo may break sniprun for all the users, I'd like to merge and make a new release when I have enough time to respond if something goes wrong (= hotfix the potential issue); so you may have to wait a little (a matter of a few days at most).

**Comment by axrt** [comment]
Sounds great, thanks!
No worries, I am fine for now cuz I compiled manually, and `sniprun` works fine
for me at the moment, I also forked the repo, will open a pr as soon as I get a
chance, but that might also take a couple of days due to that this week might be
pretty intense at work.

**Comment by axrt** [comment]
Cool, thanks!
