### ISSUE TITLE
The error log is not complete

### ISSUE THREAD

**Issue by ez4lionky** [michaelb/sniprun#166]
I use sniprun as a convenient way to run my whole script and check if the results are correct. 
But the output is not the full version of the interpreter diagnosis (print in the vertical terminal):
![Screenshot from 2022-06-17 20-21-12](https://user-images.githubusercontent.com/23551503/174297121-6bdcf91d-aa3e-4b67-b4f6-a8749825041e.png)

The output if I run the same script by using the command line:
![Screenshot from 2022-06-17 20-24-13](https://user-images.githubusercontent.com/23551503/174297572-d037e219-db94-4e00-ab6e-769618084278.png)

The full log is not important if we select several lines and then run it. But it will be convenient when we run the full script and try to debug. Is there any way to configure the output to print the full error log from the interpreter?

**Comment by michaelb** [comment]
Hey!

Unfortunately, there isn't a way to display the whole error _yet_ , but there is no reason this should stay like this forever.
I think a simple configuration switch is all we need, so it shouldn't be too long. Working on it

Note that this would only be possible in some display modes. "VirtualText" should absolutely not display the full error, while "Terminal" and "LongFloatingWindow" are no-brainer eligible

**Comment by ez4lionky** [comment]
> Hey!
> 
> Unfortunately, there isn't a way to display the whole error _yet_ , but there is no reason this should stay like this forever. I think a simple configuration switch is all we need, so it shouldn't be too long. Working on it
> 
> Note that this would only be possible in some display modes. "VirtualText" should absolutely not display the full error, while "Terminal" and "LongFloatingWindow" are no-brainer eligible

OK. I'm looking forward to the new commit about this feature :)
I believe it definitely will bring convenience when we debug.

**Comment by michaelb** [comment]
Actually, the length of the error messages are decided by each interpreter, not the display mode (though display mode may introduce additional constraints)

I'm introducing an _interpreter\_option_ that will be available to almost every interpreter and that will either force long messages or try for short ones. The default, 'auto', will try for short messages if the input is short (< 4 lines), either will prefer long ones.

When v1.2.5 gets released (soon), you should not have to modify your configuration, but in case the default doesn't sits right with you, you can always specify a different one like in the example in the README for your current interpreter

**Comment by michaelb** [comment]
v1.2.5 is out with changes allowing to configure this kind of behavior
![Screenshot_112](https://user-images.githubusercontent.com/44144536/174448418-8cc46898-87c4-4789-b307-ca8078574dd0.png)

If you're running whole files (>4 lines), the default behavior is now to show the whole error

**Comment by ez4lionky** [comment]
Got it!
