### ISSUE TITLE
Feature request: More display options for live mode

### ISSUE THREAD

**Issue by yingzhu146** [michaelb/sniprun#168]
**Is your feature request related to a problem? Please describe.**

Live mode is especially useful when parsing large data structures (e.g. tables, many newline delimited outputs etc) interactively.
This is my primary usecase (load file/stdin into var via SnipRun, then enable live mode to parse it down really quickly - I do this via https://github.com/gpanders/ijq or https://github.com/akavel/up (via --unsafe-full-throttle) (and https://github.com/HiPhish/awk-ward.nvim/for awk in neovim) right now, but ideally would love to do all of this in neovim with sniprun.

My understanding is that  Live mode is always using virtual text - I'd much rather have a vertical split here since I very rarely use live mode with single line output lines

**Describe the solution you'd like**
I'd love SnipLive to open a vertical split which automatically updates with the output -  i don't need to see the code that has been run

**Comment by michaelb** [comment]
Sounds like a good idea

**Comment by michaelb** [comment]
fixed by #182 

there's documentation in the live_mode special doc, but in your use case I can already provide a configuration key:

```
live_display = {"Terminal"}
```
