### ISSUE TITLE
Support for TSX / JSX

### ISSUE THREAD

**Issue by brenoprata10** [michaelb/sniprun#169]
I'd like to add support to `tsx` and `jsx` files, they should work out of the box with the current solution you are already using for javascript.

I have a react project and SnipRun works great on my JS files, but on my tsx files it does not work and i do not have any output.

Thanks for your great work and contribution

**Comment by michaelb** [comment]
If there is no difference (from the semantic point of view) between js and jsx, you should be able to use the same sniprun "interpreter" for both.

Handy commands:

`:SnipInfo `

(from a js file to determine what JS 'interpreter' you're using if you don't know)

`:set ft?`

to get the jsx and tsx filetypes (probably 'jsx' and 'tsx')

And configuring sniprun to use your JS interpreter should look similar to the README's config example:

```
GFM_original = {
     use_on_filetypes = {"markdown.pandoc", "anotherfiletype"}
 },
```

**Comment by brenoprata10** [comment]
I tried:
![image](https://user-images.githubusercontent.com/26099427/175920943-357de5e5-4ee3-4769-b0d3-ddd2d32f14d9.png)
But now it's not working even for ts files :p

**Comment by brenoprata10** [comment]
Nevermind, i was missing ts-node, it's working great now, thanks for your help :)
