### ISSUE TITLE
Support for Clojure

### ISSUE THREAD

**Issue by usmcamp0811** [michaelb/sniprun#173]
**Describe the language you want support for (compiler, specificities)**
I'm just starting out in Clojure and it seems like this would be a great tool for it! 
I'd like an interpreter for Clojure that uses Clojure [and that work with detected filetypes *.clj and in markdown code blocks]...

**Support Level to achieve**
Basic REPL like functionality is all I need. 

**Additional context**
[Clojure Official Page
](https://clojure.org/)

**Comment by michaelb** [comment]
I'll try to do that, but mind that 

> Basic REPL like functionality is all I need.

this 'basic' functionality can be very difficult to implement if the language's interpreter is quirky and has unusual stdin/stdout behavior (and we can't know till I try)

 Bloc level (maybe Import level) is all I can 'guarantee'

**Comment by michaelb** [comment]
There's some work on the dev branch

If you want to test (and give feedback), it's possible though not top-tier-newbie-friendly:

- you'll need the Rust toolchain
- install the dev version by specifying to your plugin manager the "dev" branch and to use this command as post-install script: `bash ./install.sh 1` (note the '1')
- configure sniprun to enable REPL for the new Clojure_fifo interpreter (repl\_enable={'Clojure_fifo'}, see configuration section in readme)

Whatever you do, I'll take a few days to create tests and polish the new interpreter, and make a new release after that
