### ISSUE TITLE
[Just a noob question] Can't figure out how to get Terminal support

### ISSUE THREAD

**Issue by alexhallam** [michaelb/sniprun#179]
**Describe the bug**
I cant activate terminal mode

**What do the bug concerns? Sniprun itself, a particular interpreter?**

Just trying to set up for the first time

**To Reproduce**

This is my full `init.lua`. The `SnipRun` command works, but the results are inline as opposed to in a Terminal on the side.

```lua
local o = vim.o

o.number = true
o.termguicolors = true

-- local ok, _ = pcall(vim.cmd, 'colorscheme everforest')
local ok, _ = pcall(vim.cmd, 'colorscheme melange')

return require('packer').startup(function()
    use 'sainnhe/everforest'
    use 'savq/melange'
    use 'scrooloose/nerdtree'
    use 'itchyny/lightline.vim'
    use 'easymotion/vim-easymotion'
    use {'michaelb/sniprun', opt = true, cmd = { 'SnipRun' }, display = {'Terminal'}, run = './install.sh' }
    use {
  	'lewis6991/gitsigns.nvim',
		config = function()
    		require('gitsigns').setup()
  	end
	}
    use {'hkupty/iron.nvim'}
	
end)
```

**Expected behavior**

Just want the Terminal output on the side

**Screenshots**

![image](https://user-images.githubusercontent.com/9298693/192530128-984e7d62-369b-4107-bc1c-a5978f1e7fda.png)

**Environment:**
 - Neovim version: `NVIM v0.7.2`
- OS/distribution: `Debian 11`
- if possible, GLIBC version (output of `ldd --version`): `(Debian GLIBC 2.31-13+deb11u4) 2.31`

**Comment by michaelb** [comment]
No worries

This is just the wrong place to add ` display = {"Terminal"}`

You should have, after the packer snippet (or better, in another file -then sourced from init.lua- like many other plugins suggest) this kind of code:

```
require('sniprun'). setup({
    display = {"Terminal"},
})
```
