### ISSUE TITLE
Cannot be used properly in ts files

### ISSUE THREAD

**Issue by Athrun-Judah** [michaelb/sniprun#185]
**Describe the bug**
I get an error when I run `:SnipeRun`. The error message is `RuntimeError: TSError: x Unable to compile Typescript:`. And no more error messages. But this is fine if I'm running the file with ts-node.

**Screenshots**
This is my config.
![WindowsTerminal_4mLmRO9KO4](https://user-images.githubusercontent.com/66123941/195491518-2ccf97c9-df0a-47d6-9d94-b10508110c09.png)

**Environment:**
 - Neovim version [v0.7.2]
- WSL Ubuntu22.04

**Comment by michaelb** [comment]
Hello!

Thanks for the bug report, it's true that this error message looks a bit confusing.

Could you provide the snippet you're trying to run?

**Comment by Athrun-Judah** [comment]
> 
A simple piece of code. 

![WindowsTerminal_rcxj2FsYv8](https://user-images.githubusercontent.com/66123941/195514600-b4010c69-e07a-486b-9c99-f216ad8804cf.png)

**Comment by michaelb** [comment]
Hmm did you run `:SnipRun` on only one line (that would be invalid on its own)?

Visual-selection of both lines + `:'<,'>SnipRun` ought to work

If not, I'll look into it this evening

**Comment by Athrun-Judah** [comment]
If the cursor is not in the `console.log(message)` running `:Sniprun` on this line will output `(no output)`. `:'<,'>SnipRun` and `:SnipRun` have the same phenomenon.

**Comment by michaelb** [comment]
> If the cursor is not in the console.log(message) running :Sniprun on this line will output (no output).

That's to be expected: `let message: string = 'hello'` does not print anything no there is no output.


Unless you enable REPL (not always available, see `:SnipInfo`, `:SnipInfo <some interpreter>`, the README of this repo), sniprun has no 'memory' of lines you previously sniprun'd. So you cannot run those two lines separately and have 'hello' as output.

If you _select_  both those lines in **visual mode**, and run `:'<,'>Sniprun` over that it should work :-)

**Comment by Athrun-Judah** [comment]
Thank you for your patient reply. I watched `:SnipInfo` but js and ts don't seem to support REPL. Still, your plugin helps me a lot of the time :-)

**Comment by michaelb** [comment]
So you did make the simple example works? Nice :-)

There is a REPL-capable TypeScript-compatible interpreter: JS_TS_deno. Not the default for TS since it has additionnal requirements (see `:SnipInfo JS_TS_deno`), but may be worth setting up

Feel free to close this issue when everything works
