### ISSUE TITLE
Run an interpreter from a different type than current filetype

### ISSUE THREAD

**Issue by teto** [michaelb/sniprun#197]
**Is your feature request related to a problem? Please describe.**

Nix is not supported at the moment (`RuntimeError: Generic interpreter (!): Language 'nix' is not supported`) but I wanted to run a few shell commands from comments, i.e. I have the cursor at the start of "systemctl" in
```
 # file ntp.nix
  services.chrony = {
    # if time is wrong:
    # 1/ systemctl stop chronyd.service
    # 2/ "sudo chronyd -q 'pool pool.ntp.org iburst'"
    enable = true;
  };
```
would like to run `SnipRun bash` with `systemctl stop chronyd.service` 

**Describe the solution you'd like**
seems like `SnipRun` could accept the interpreter to send to ? (maybe the underlying lua function can dot it, not sure).

Note: I've in my init.lua sniprun.setup
```
	interpreter_options = {         --# interpreter-specific options, see docs / :SnipInfo <name>
		Base_original = {
			use_on_filetypes = {"nix"}    --# the 'use_on_filetypes' configuration key is
		}
```

**Comment by michaelb** [comment]
tdlr: 
what you want is not achievable by sniprun 


anti-tldr:
Unless it's a typo in your comment, the name of the Bash interpreter is Bash_original, not Base_original (just in case)

`:SnipInfo` should tell you what interpreter is active for the current filetype

Though, sniprun cannot operate at finer granularities than the line, so you'll send the initial '#' along with the rest of ypur command, and it'll be interpreted as a comment. Sorry 😅
