### ISSUE TITLE
Allow setting sniprun binary location

### ISSUE THREAD

**Issue by nikicoon** [michaelb/sniprun#205]
If I package the application part of the plugin and it installs to my $PATH, I have to symlink the binary into the fixed location of the plugin.
It would be good if you'd allow overriding the location via a config option.

**Comment by michaelb** [comment]
Currently in dev branch :-), this wasn't too hard.

Set the (undocumented for now) binary_path config option
```
require('sniprun').setup({
binary_path="/path/to/your/sniprun",
})
```

Simply specifying 'sniprun' and having the binary on your $PATH also works.


You can try it out now by setting your plugin manager to track the 'dev' branch of this repo, or wait for the next release (that I'll publish in less than 15 days I think)
