### ISSUE TITLE
Error while executing 'SnipRun' command

### ISSUE THREAD

**Issue by ZakharovOleg** [michaelb/sniprun#206]
NVIM version: NVIM v0.8.2 (AstroNvim configuration)
Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Locale: en_US.UTF-8
OS description: Ubuntu 22.04.1 LTS

What could be wrong?

[<a href="https://imageup.ru/img22/4164036/im1.png.html" target="_blank"><img src="https://imageup.ru/img22/thumb/im14164036.jpg" border="0" alt="фотохостинг без рекламы"></a>](url)

[<a href="https://imageup.ru/img168/4164038/im2.png.html" target="_blank"><img src="https://imageup.ru/img168/thumb/im24164038.jpg" border="0" alt="хостинг для хранения изображений"></a>](url)

**Comment by michaelb** [comment]
`: checkhealth sniprun` should gives us more info

It usually boils down to either:
- the sniprun binary wasn't properly downloaded at install time
- the prebuilt binary is for some reason incompatible (are you on Mac, an ARM CPU...?)

**Comment by ZakharovOleg** [comment]
Thanks for your assistance!

CPU: AMD A9-9425 RADEON R5 2C+3G (2)
GPU: AMD ATI Radeon R2/R3/R4/R5 Grap

[<a href="https://imageup.ru/img185/4164242/im3.png.html" target="_blank"><img src="https://imageup.ru/img185/thumb/im34164242.jpg" border="0" alt="Бесплатный хостинг фотографий"></a>](url)

**Comment by ZakharovOleg** [comment]
Voila, we have done it! Thanks a lot!
It took to reinstall plugin twice (screenshot is added).
The hint is to run 'install.sh' after plugin reinstallation to collect all the files.

[<a href="https://imageup.ru/img147/4164355/im4.png.html" target="_blank"><img src="https://imageup.ru/img147/thumb/im44164355.jpg" border="0" alt="хостинг фото"></a>](url)

**Comment by michaelb** [comment]
Maybe you have a particularly shady internet connection? But yes (as documented) `./install.sh` _has_ to be run
Happy you got it working, I'll close this issue
