### ISSUE TITLE
Escape code not stripped maybe?

### ISSUE THREAD

**Issue by ryuheechul** [michaelb/sniprun#213]
**Describe the bug**
Escape code not stripped

**To Reproduce**
1. Open a typescript file containing '1+1'
2. Run the command ':SnipRun'
3. See error escape code contained as below

```
1+1 <- ^[[33m2^[[39m
```

**Expected behavior**

I expect no escaped code like this in virtual text, `1+1 <- 2` instead

**Screenshots**
<img width="222" alt="Screenshot 2023-03-09 at 9 50 08 PM" src="https://user-images.githubusercontent.com/2637709/224234261-d9181a0a-faed-49c0-b39e-a8ffecf931be.png">

**Environment:**
- Neovim: v0.8.3
- OS/distribution: macOS 13.2.1 22D68 arm64
- SnipRun: https://github.com/michaelb/sniprun/releases/tag/v1.2.10

**Additional context**
- my Neovim config regarding sniprun: https://github.com/ryuheechul/dotfiles/commit/52a90a6ab5c74c9fe790c6e03f61fd85f0b0bbbb
- GitHub code search with `escape` in this repo: https://github.com/search?q=repo%3Amichaelb%2Fsniprun%20escape&type=code

**Comment by ryuheechul** [comment]
### Additional context
<img width="225" alt="Screenshot 2023-03-09 at 11 16 12 PM" src="https://user-images.githubusercontent.com/2637709/224248959-e1d88ad1-f17c-4df2-8730-47227ef79e76.png">

It looks like sometimes it doesn't have escape code and sometimes do.
For the particular screenshot above, the difference seems whether it's wrapped in `console.log` in the same line or not.

**Comment by michaelb** [comment]
Hey, thanks for the bug report

So I assume you're in REPL mode ?
I probably forgot to pass options to the actual REPL to tell it not to color its stdout

Looking into this this weekend

**Comment by michaelb** [comment]
Fix shouldn't be long, and I'll be putting out a new version (v1.2.11) soon

Meanwhile, you can export the environnement variable `NO_COLOR=1` which is respected by deno to no output ANSI color codes in its REPL (used directly by sniprun)

**Comment by ryuheechul** [comment]
Sorry for the delayed response, yes it was for the deno REPL. Just verified that the fix works like a charm, thanks a lot!
