### ISSUE TITLE
Error on api.lua:12 when executing SnipLive

### ISSUE THREAD

**Issue by serhez** [michaelb/sniprun#215]
**Describe the bug**
When executing the `SnipLive` command (with the live mode being enabled in the config), I get the error: 

`Error  E5108: Error executing lua ....local/share/nvim/lazy/sniprun/lua/sniprun/live_mode.lua:37: nvim_exec(): Vim(lua):E5108: Error executing lua ...s/ser/.local/share/nvim/lazy/sniprun/lua/sniprun/api.lua:12: attempt to index field 'config' (a nil value)`

I believe you are using `M.config` in api.lua:12, which is not defined, and should instead use `lconfig`?

**To Reproduce**
1. Enable the live mode in the config via `live_mode_toggle = "enable"`
2. Run the command `SnipLive`.
3. See error above

**Expected behavior**
No error

**Screenshots**
N/A.

**Environment:**
- Neovim nightly
- MacOS latest

**Comment by michaelb** [comment]
looks like I broke this on the v1.2.10 version while attempting to solve #205

Fortunately, it's an easy fix (M.config -> sniprun.config_values). Releasing v1.2.12 ASAP

**Comment by serhez** [comment]
Thanks @michaelb !

**Comment by michaelb** [comment]
We're both unlucky in that SnipLive is one of the few things not quite tested (automatically in the CI) and that I just released a previous version a few hours back

Merging the linked PR will close this issue, and a new release should be created a few minutes after that.

Feel free to reopen it if you still have a related issue :smile:
