### ISSUE TITLE
SnipInfo Command  Error and Unable to receive user input.

### ISSUE THREAD

**Issue by rileychc** [michaelb/sniprun#222]
**Describe the bug**

**To Reproduce**
1. Open a file containing '...'
2. Run the command '....'
3. See error '...'

**Expected behavior**

**Screenshots**

**Environment:**
 - Neovim version [e.g. v0.6.1]
- OS/distribution

**Additional context**

**Comment by michaelb** [comment]
Hey, please fill correctly your bug report.

SnipInfo works on my end (I would be tempted to say 'obviously'), so unless you provide me with enough info, I won't be able to fix your issue

**Comment by rileychc** [comment]
~/.cache/sniprun/infofile.txt， I don't have this document

**Comment by rileychc** [comment]
But my main problem is that I still can't pop up to receive user input, causing my cin function to be a random value.

**Comment by michaelb** [comment]
> But my main problem is that I still can't pop up to receive user input, causing my cin function to be a random value.

That's a limitation of sniprun. It won't be fixed in the near future

> ~/.cache/sniprun/infofile.txt， I don't have this document

It's supposed to be generated, and I hardly see where it can fail. Could you copy here the content of ~/.cache/sniprun/sniprun.log after trying to run SnipInfo ?

**Comment by rileychc** [comment]
I can't find the sniprun folder in the .cache folder.

**Comment by michaelb** [comment]
> I can't find the sniprun folder in the .cache folder.

Wut. Does sniprun even work ? (Run it on a very simple line such as "print(1)" in a python file)

Or do you have an $XDG_CACHE_DIR environment variable that's set to somewhere strange ?

**Comment by rileychc** [comment]
I didn't set this $XDG_CACHE_DIR environment variable, and my sniprun can output printf("hello world");

**Comment by rileychc** [comment]
I'm using macOS.

**Comment by rileychc** [comment]
So what should I do? Specify the path XDG_CACHE_HOME in the zshrc file, or should I make other settings?

**Comment by michaelb** [comment]
I think you should specify the XDG_CACHE_DIR in your shell's rc configuration file, but preferably make it point to the value of the default cache directory on macos (google says it's ~/Library/Caches, and if you find a sniprun subdir there it's confirmed).

I'll fix the search path for the infofile, but the above should fix the issue in the meantime

**Comment by rileychc** [comment]
<img width="574" alt="image" src="https://user-images.githubusercontent.com/116857974/232767036-e01ae140-182a-4bea-a2b5-6434f083bddb.png">
It isn't useful.

**Comment by michaelb** [comment]
`XDG_CACHE_HOME` 😉

**Comment by michaelb** [comment]
The last release also search for the temporary SnipInfo file in ~/Library/cache now, so it should be automatically fixed
