### ISSUE TITLE
No help for sniprun

### ISSUE THREAD

**Issue by Leixb** [michaelb/sniprun#223]
**Describe the bug**

`:help sniprun`  fails with: `E149: Sorry, no help for sniprun`

**To Reproduce**

1. Install `sniprun` 
2. run `:h sniprun`
3. no help is shown.

**Expected behavior**

The help file `sniprun.txt` opens.

**Environment:**
- Neovim version `NVIM v0.10.0-dev-3c724fe`
- NixOS

Tested both NixOS installation and vim-plug and the issue occurs on both cases.

**Additional context**

The issue is caused by `sniprun.txt` being in `docs` instead of `doc`.

I have worked around the issue in nixpkgs by linking `doc/sniprun.txt` into `docs/sniprun.txt`: https://github.com/NixOS/nixpkgs/pull/225786

**Comment by michaelb** [comment]
Thanks for the bug report (and the solution)
It looks like something changed on neovim's side, because it definitely worked before.

But ut'd not something I deemed worth testing.... Maybe I should have

I'll fix this soon!

**Comment by michaelb** [comment]
solved by the latest 1.3.1 release.

Maybe you want to update the version of sniprun on the nixpkg repos ? (idk how the nixos stuff works)

**Comment by Leixb** [comment]
> Maybe you want to update the version of sniprun on the nixpkg repos ? (idk how the nixos stuff works)

I just did, thanks!
