### ISSUE TITLE
Wiki pages not working (404)

### ISSUE THREAD

**Issue by Inom-Turdikulov** [michaelb/sniprun#244]
**Describe the bug**
When I open wiki page, I recive 404 error
https://michaelb.github.io/sniprun/

**To Reproduce**
Open [wiki page](https://michaelb.github.io/sniprun/)

**Screenshots**
![image](https://github.com/michaelb/sniprun/assets/3938577/592251e0-bb36-4ca2-8298-8429293e2fb0)

**Comment by michaelb** [comment]
looking into it

wtf github
