### ISSUE TITLE
Bun Repl

### ISSUE THREAD

**Issue by greidinger-reis** [michaelb/sniprun#262]
**Describe the language you want support for (compiler, specificities)**
I'd like an interpreter for Typescript/Javascript that uses Bun `bun repl` [and that work with detected filetypes javascript, typescript]...

**Support Level to achieve**
Any support is enough for me....

**Additional context**

**Comment by michaelb** [comment]
I guess that you also want REPL capabilities within sniprun, as," it's possible to run a snippet declaring one variable, and then another one using it" ?

If so, I can implement that, but I'll need some time and luck

If you don't require REPL capabilities,  it should be possible to get it running by yourself with the [generic interpreter](https://michaelb.github.io/sniprun/sources/interpreters/Generic.html)

**Comment by greidinger-reis** [comment]
Well, ofc REPL capability would be nice, but in the mean time, I tried to use the generic interpreter, but the Typescript_original is run instead.

my config:
```lua
config = function()
            require("sniprun").setup({
                interpreter_options = {
                    Generic = {
                        Bun = {
                            supported_filetypes = { "typescript" },
                            extension = ".ts",
                            interpreter = "bun repl",
                            compiler = "",
                        }
                    }
                },
                selected_interpreters = { 'Generic' },
            })
        end,
```

![image](https://github.com/michaelb/sniprun/assets/62309738/023e491c-a4b7-48ee-8c56-837b59148c22)

**Comment by michaelb** [comment]
There is indeed an error in my current code driving behavior of sniprun when the Generic interpreter is used on a language that already has support. Something not too complex, but since you'll wait anyway I can make a proper TS/JS Bun intepreter... and maybe REPL-capable
