### ISSUE TITLE
C+OpenGL ERROR

### ISSUE THREAD

**Issue by chenhui2016** [michaelb/sniprun#266]
**Describe the language you want support for (compiler, specificities)**
I'd like an interpreter for OpenGL that uses <clang>

The following is a configuration file for OpenGL in C language.
![image](https://github.com/michaelb/sniprun/assets/66300288/696509a1-7a22-4dd7-8cf2-5a8fcb7249bc)
When I run the following error with SnipRun, but there is no problem with terminal compilation and operation, how should I solve it？
![image](https://github.com/michaelb/sniprun/assets/66300288/75442493-0b72-4e0b-97fb-8e94f84cff44)

**Comment by michaelb** [comment]
well, not excluding other potential issues, but for starters the "compilation_options" configuration field doesn't exist.

You should have better results adding your flags to the compiler argument itself, as shown in the [wiki](https://michaelb.github.io/sniprun/sources/interpreters/Cpp_original.html)
