### ISSUE TITLE
Does not seem to work properly

### ISSUE THREAD

**Issue by hsanson** [michaelb/sniprun#38]
**Describe the bug**

1. Open small python hello world
2. Visual select all the code
3. Run SnipRun
4. See error about non existent channel.

```
Error detected while processing function <SNR>42_run:                 
line    3:
E475: Invalid argument: Channel doesn't exist
Press ENTER or type command to continue
```

**What do the bug concerns? Sniprun itself, a particular interpreter?**

Tried also Ruby and Bash sample Hello World programs. Same result.

**Expected behavior**

I expected to see a terminal magically being open with the required REPL and get the selected code executed in it.

**Screenshots**

![image](https://user-images.githubusercontent.com/900716/106460037-13a08d00-64d6-11eb-9d3f-02e114614719.png)

**Environment:**

 - Linux (Kde Neon Latest)
 - Neovim v0.5.0-dev+1019  (Latest compiled from master)

**Comment by michaelb** [comment]
Hi, this is quite....strange

I'm also on neovim@latest, and everything runs fine (you CAN'T be missing a bash interpreter, right?)

So, my guess is that for some reason (did you read the 'installation' part?), the install.sh script was not run, and thus you are missing a part of the project that deal with the receiving side of the RPC Channel; hence the error

**Comment by hsanson** [comment]
Seems to be an issue with library compatibility?

SnipRun binary installs correctly:

```
[~/.config/nvim/bundle/sniprun]$ ./install.sh 
Runnning Sniprun Installer
Trying to get a up-to-date precompiled binary
Downloading binary..
Done
```

But running it fails:

```
[~/.config/nvim/bundle/sniprun]$ target/release/sniprun 
target/release/sniprun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by target/release/sniprun)
```

Seems the precompiled binary it downloads is no good for my installation.

I already have the libc6-dev package installed so is a version compat issue.

**Comment by michaelb** [comment]
That's quite interesting.
The only non-fully-rust dependency has been removed as of 0.4.6, so you may want to retry now

Using cc="*" was necessay at some point, but not anymore, and it has external bindings to C libraries, so it may be the root of the problem. Unfortunately, our distributions differ (hence the problem) and I can't reproduce

If that does not fix this issue, I see no other solution than to tell the install script to compile sniprun locally (set "1"as argument to the install script as mentionned in the installation part), though it also require the rust toolchain

**Comment by michaelb** [comment]
Hi, has the patch (or the workaround, was it necessary?) worked for you?

I'd like to close this issue and update adequately the README :-)

**Comment by hsanson** [comment]
Compiled locally and seems to work fine. This can be closed.
