### ISSUE TITLE
Support text-objects

### ISSUE THREAD

**Issue by hsanson** [michaelb/sniprun#39]
Using visual mode to select text for SnipRun is not an efficient vim workflow. 

Implementing support for text-objects can be complex. An easier way would be to ensure the SnipRun function works properly with the toop#mapFunction() method of [vim-toop](https://github.com/jeanCarloMachado/vim-toop).

**Comment by michaelb** [comment]
Nice idea !

Sniprun will probably never be able to execute _part_ of a line, and anyway such code would probably be incorrect semantically.

I probably just need to support line-wise motions, if that's a few lines of code i'd rather not depend on another plugin

**Comment by michaelb** [comment]
implemented by @DarwinSenior 's #55 PR
