### ISSUE TITLE
Import support level for C

### ISSUE THREAD

**Issue by michaelb** [michaelb/sniprun#47]

**Comment by michaelb** [comment]
https://user-images.githubusercontent.com/57088952/111072753-e86a7e00-8516-11eb-9cdd-b25d2dee07a7.mp4

_Originally posted by @denstiny in https://github.com/michaelb/sniprun/issues/45#issuecomment-798919844_


This behavior would be practical !

**Comment by michaelb** [comment]
Barring the fact that quite strangely, there is no error message, having import support level for C should not be harder that copypasting C++ interpreter code, so why not do it?

**Comment by denstiny** [comment]
I think it should be no problem

**Comment by michaelb** [comment]
![Screenshot_20210314_155553](https://user-images.githubusercontent.com/44144536/111073097-b852b900-84dd-11eb-94a1-ca6e79a7542d.png)

I'm still a bit concerned that you don't have error messages like this when the code fail to compile

**Comment by michaelb** [comment]
> I think it should be no problem

I'll look into that shortly

**Comment by michaelb** [comment]
> I think it should be no problem

I'll look into that shortly

**Comment by denstiny** [comment]
> ![截图_20210314_155553](https://user-images.githubusercontent.com/44144536/111073097-b852b900-84dd-11eb-94a1-ca6e79a7542d.png)
> 
> 我仍然有点担心，当代码无法编译时，您没有像这样的错误消息（带有适当的错误ofc）

In addition I have not received any error

**Comment by denstiny** [comment]
What can I do for you？

**Comment by denstiny** [comment]
![image](https://user-images.githubusercontent.com/57088952/111073341-48622400-8519-11eb-8f39-4fe1adb19b16.png)


In fact, when running a little bit complicated code without any output

**Comment by denstiny** [comment]
Similar to the c language to implement the already very difficult, so don't lose heart

**Comment by michaelb** [comment]
![Screenshot_20210314_160745](https://user-images.githubusercontent.com/44144536/111073522-601cb680-84df-11eb-8ef0-a149c5dc63b6.png)

This particular code is invalid (i guess, you should initialize s and malloc it some memory) , so Sniprun try do diusplay an error - and that doesn't work for you, which is what 'ill try to debug)

**Comment by michaelb** [comment]
Sniprun relies on nvim_err_write ( a neovim function) to display an error.

Could you try to run 

`:call nvim_err_write("line1\nline2\n")`

**Comment by denstiny** [comment]
![image](https://user-images.githubusercontent.com/57088952/111073890-8d875580-851b-11eb-9e4f-a33c5a297f40.png)


> ![Screenshot_20210314_160745](https://user-images.githubusercontent.com/44144536/111073522-601cb680-84df-11eb-8ef0-a149c5dc63b6.png)
> 
> This particular code is invalid (i guess, you should initialize s and malloc it some memory) , so Sniprun try do display an error - and that doesn't work for you, which is what I'll try to debug)

**Comment by denstiny** [comment]
> Sniprun依靠nvim_err_write（neovim函数）来显示错误。
> 
> 你能跑吗
> 
> `:call nvim_err_write("line1\nline2\n")`
> 
> （来自neovim）？

I can't run him
![image](https://user-images.githubusercontent.com/57088952/111074339-7b0e1b80-851d-11eb-800c-b432258a98cb.png)

**Comment by michaelb** [comment]
The code itself is (again) invalid, so I wonder what you have run this time.

I guess you've run `:call nvim_err_write("4\n7\n") `, and in this case it makes sense, but that also means nvim_err_write works..... but not when run from sniprun

**Comment by denstiny** [comment]
> 该代码本身（再次）无效，所以我想知道您这次运行了什么。
> 
> 我猜你已经运行了`:call nvim_err_write("4\n7\n") `，在这种情况下这很有意义，但这也意味着nvim_err_write可以工作...但是从sniprun运行时则不行

Well, I run Sniprun error code won't give me any mistake, I'm sorry, I ability is limited, can only help you so much, can reply to me if there is any need, I should go to bed

**Comment by michaelb** [comment]
no worries, you can get in touch anytime. Though, this is a side project and i'm also working on other things, idk if i'll be able to debug your (pretty but) particular neovim

**Comment by denstiny** [comment]
> no worries, you can get in touch anytime. Though, this is a side project and i'm also working on other things, idk if i'll be able to debug your (pretty but) particular neovim
> 

I didn't understand your last sentence. Debug my neovim? What do you mean?

**Comment by michaelb** [comment]
It looks like Sniprun does not display correctly (if at all) on your config, whereas it works on mine and a friend's.

If we want to understand why, we'll have to take some time to search for the cause and solution

**Comment by denstiny** [comment]
> It looks like Sniprun does not display errors correctly (if at all) on your config, whereas it works on mine and a friend's.
> 
> If we want to understand why, we'll have to take some time to search for the cause and solution

Do you want to install my configuration to try to find the problem?

**Comment by michaelb** [comment]
Sure, if you have any dotfiles that would be great, and I'd also like to check your neovim version. 

I won't do it right away though, you've mentionned you wanted to go to sleep and you should take care of yourself, open-source is great but also a rabbithole

**Comment by denstiny** [comment]
You are so thoughtful, I think the installation is very simple at least, But I did not do English documents, if you can, try to translate Chinese into English, encounter installation problems at any time to reply to me, I try to help you.
地址        https://github.com/denstiny/nvim-nanny

**Comment by denstiny** [comment]
> no worries, you can get in touch anytime. Though, this is a side project and i'm also working on other things, idk if i'll be able to debug your (pretty but) particular neovim
> 

Is it possible that I'm using a preview version of neovim?

**Comment by michaelb** [comment]
A recent version should not create problems (whereas an older one....), and i'm on nightly 0.5 myself

**Comment by michaelb** [comment]
I successfully reproduced and I've worked through some kind of workaround, though the exact cause of the issue remains a mystery. 

You should set a new config variable, `let g:SnipRun_inline_messages=1`, that , while it breaks multi-line support that wasn't there for you in the first place, does now display, more or less nicely, output & errors.

To try that before it gets a release, you can set your plugin manager on the dev branch, and run the post-install script `bash ./install.sh 1`

**Comment by denstiny** [comment]
> I successfully reproduced and I've worked through some kind of workaround, though the exact cause of the issue remains a mystery. 
> 
> You should set a new config variable, `let g:SnipRun_inline_messages=1`, that , while it breaks multi-line support that wasn't there for you in the first place, does now display, more or less nicely, output & errors.
> 
> To try that before it gets a release, you can set your plugin manager on the dev branch, and run the post-install script `bash ./install.sh 1`
You are great, but unfortunately I can't run it because of the network.

 trust you know what you're doing, just don't forget to run ./install.sh, or alternatively, cargo build --release


This code.     cargo build --release

**Comment by denstiny** [comment]
I'll try setting'g: SnipRun _ inline _ messages'

**Comment by denstiny** [comment]
I am sorry that I did not receive an error message, I think it is not important, because this error is caused by the programmer, and not your plugin
I set up the let g: SnipRun_inline_messages = 1
I think I should be running bash. \/ install. Sh 1
But I can't run him, not because of my network

**Comment by michaelb** [comment]
if bash ./install.sh 1 try to download something, it's because you don't have the Rust toolchain installed.

I've tested with your config, didn't work before, and now works with g:SnipRun_inline_messages=1, so the working code is already written!

However I didn't have the time to make a new release with an updated (pre-compiled) binary, and I'm working right now

**Comment by denstiny** [comment]
ok,Thank you very much

**Comment by michaelb** [comment]
I've tried, and it works with your config.

Though ,it's not as pretty as on mine because of some colorscheme shenanigans, still very usable.

Be sure to update to v0.4.9, no need to get the dev branch or give '1' as arg to the install script.

**Comment by denstiny** [comment]
> 我已经尝试过了，它可以与您的配置一起使用。
> 
> 虽然，由于某些颜色设计的恶作剧，它不如我的漂亮，但仍然非常有用。
> 
> 确保更新至v0.4.9，无需获取dev分支或将'1'作为arg赋予安装脚本。


You really are a very, head of the author

**Comment by michaelb** [comment]
No worries, I'll close this issue if you don't have any new problems :-)

**Comment by yingzhu146** [comment]
This doesn't appear to work for me btw -

test case:

```c
#include <stdio.h>
int ret(int i){
	return i;
}

int main(void) {
    int res = ret(2);
    printf("hello %i", res); 
    return 0;
}
```
```vim
exe '! gcc ' . expand("%") . ' -o ' . expand("%")[:-3] .'.o && ' . expand("%")[:-3] . '.o' 
hello world 2
```

Hovering on the `printf` line:

```vim
:<,>SnipRun
Compile-time error: use of undeclared identifier 'res'
    printf("hello %i", res);
Press ENTER or type command to continue
```

**Comment by michaelb** [comment]
that's expected behavior.

While your one-liner run the entire file (and depends on its semantic correctness), at Import support level, sniprun only has knowledge about the code you selected.

In this case, `:'<,'>SnipRun` has no knowledge about 'res', let alone 'ret'. 
However running sniprun on a visual selection containing 
```c
int a = 3;
printf("hello %i \n", a);
```
will work (that's Bloc-level support)

I know that's a bit of a shame because verbose languages such as C often have many dependencies on non-contiguous parts of code, however getting these 'dependencies' is a very complicated task (though not impossible), because I want that to work even if some parts of the code are still incomplete/ incorrect

**Comment by yingzhu146** [comment]
I see - thank you! Ah yeah okay I should've RTFM a bit more closely. What's your workflow for interactive running of multi-function/more complicated in  `Import` supported languages?

**Comment by michaelb** [comment]
For now, that's only possible with interpreters that have REPL capabilities, and then one can sniprun separately a function, then a print(function_call()), jupyter-notebook-style.

Unfortunately, only Python, Bash, R, Julia(wip) and Lua have such capabilitiesfor now. It's not unfeasible to give this 'REPL' capability to compiled languages, but that's not in the plans right now.


Feel free to open a feature request ofc :-)

**Comment by yingzhu146** [comment]
I see! so when e.g. working in C or C++ you mostly use this for working with imported functions and less with functions that are defined in the same file?

And for C++ (and possibly others) - there are REPLs in form of jupyter kernels right? e.g. (cling)[https://github.com/jupyter-xeus/xeus-cling/tree/1d091cafb031073fb9ce78027d6c1ca81de0c243]
