### ISSUE TITLE
Lua_nvim support

### ISSUE THREAD

**Issue by vigoux** [michaelb/sniprun#5]
Hey ! Thanks for this awesome plugin !

I think it can be really useful to execute lua snippets within neovim, how hard do you think it would be ?
And how could I help in the process ?

Thanks again !

**Comment by michaelb** [comment]
Unofficially, Lua is already supported up to line-level through the 'generic' interpreter; I have tested that you can run print("Hello World!") in lua. However, bloc-level support is not there yet.


Implementing real bloc-level support in Lua should be super-easy. In fact, I could probably implement it in ~15min, (and if you have >= beginner level skill with Rust, you can probably do it as fast, especially if you take inspiration from the Bash interpreter that should be really similar).

If you want to do it yourself, please have a look at the CONTRIBUTING.md guide and submit a PR.

If you want me to do it, just tell me and i'll make it work (up to bloc-level though)!

**Comment by vigoux** [comment]
I wasn't clear in my feature request :wink: 
I want to be able to debug and execute tiny lua pieces of codes, within the current neovim instance, so that I can see the thing evolve.
