### ISSUE TITLE
I have a good idea, hopes to add this functionality to the markdown, used to run the markdwon code block

### ISSUE THREAD

**Issue by denstiny** [michaelb/sniprun#50]
I have a good idea, hopes to add this functionality to the markdown, used to run the markdwon code block
This function is similar to the Babel of org
![image](https://user-images.githubusercontent.com/57088952/112429409-924bd500-8d77-11eb-9b84-8c026d3522ff.png)

**Comment by michaelb** [comment]
Not a bad idea, but will need some precision about what you envision. There are lots of different 'markdown' and code is defined differently, for example this #+BEGIN_SRC C and the more casual triple backtick \``` bash \<code> \```.

Babel - org is a monumental achievement and in the same time, a bit niche and somehow different from sniprun. 

It will be possible, to do one or many markdown interpreters that can ease the process of selecting 'code blocks' and send the snippet to the appropriate language interpreter!

**Comment by michaelb** [comment]
to honest though, this is not a priority in my eyes.

I'm more excited about migrating to lua, using treesitter (someday) and text-objects support.

You're welcome to have a look if you want though. It does not look as easy as creating a new interpreter, but definitively doable!

**Comment by michaelb** [comment]
it was fun to do actually, will be in 0.5.1, released when some other things satisfy me.

The current markdown interpreter is in dev  branch and is base on Github flavored markdown, but functionnality may be extended later.

```bash
echo "lol"  # << you can run sniprun on this line
```

I'm still ironing out how this should work etc...

**Comment by denstiny** [comment]
> 确实很有趣，当其他条件使我满意时，它将在0.5.1中发布。
> 
> 当前的markdown解释器位于dev分支中，基于Github风格的markdown，但功能可能会在以后扩展。
> 
> ```gfm
> ``
> 回声 “笑”   ＃ <<你可以运行sniprun在这条线
> \` ` ` 
> ```
> 
> 我仍然在熨烫这应该如何工作等等。。。

This is really great, until I'm sorry to have something didn't pay attention to the news
Thank you very much to my proposal to heart

**Comment by michaelb** [comment]
Hi, 0.5.1 is landing in master any time now, so I'm happy to announce that your use case (very useful) is covered!

Be sure to read the documentation (it can now be displayed with `:SnipInfo GFM_original` ) because the GFM interpreter (github flavored markdown) has some limitations and a configuration option.

I also strongly encourage you to enable REPL-like behavior if available for your language/interpreter of choice (yet again `:SnipInfo` ) , it's a very smooth workflow!

I'll be closing this issue soon, thanks for the nice idea!

**Comment by denstiny** [comment]
> 嗨，0.5.1现在可以随时进入master了，所以我很高兴地宣布您的用例（非常有用）已覆盖！
> 
> 请务必阅读文档（现在可以与一起显示`:SnipInfo GFM_original`），因为GFM解释器（github式markdown）具有一些限制和配置选项。
> 
> 我也强烈建议您启用类似REPL的行为（如果适用于您选择的语言/口译员`:SnipInfo`）（再次），这是一个非常流畅的工作流程！
> 
> 谢谢您的好主意，我将尽快解决此问题！

Don't mention it, this is also in order to have a better development in the sniprun

**Comment by michaelb** [comment]
#52 resolves this
