### ISSUE TITLE
[Question] Why python repl doesn't  work?

### ISSUE THREAD

**Issue by peach-lasagna** [michaelb/sniprun#60]
https://user-images.githubusercontent.com/59787538/114866009-3d9ef580-9e1d-11eb-80d4-15053ee2a92b.mp4

**Comment by michaelb** [comment]
It's indeed a very strange issue. I can't exactly the configuration but I trust it's not a typo (you can always check what interpreter is selected for the current filetype with `:SnipInfo`)

Unfortunately, i'm unable to reproduce your exact issue, however i'm having the same issue with the Julia_jupyter interpreter #59 : it's a very troublesome race condition. I'm trying to debug that, and i'll port the fix to the python3_jupyter interpreter.

I know it's a compromise, but maybe you could enable REPL for the Python3_original interpreter ? It's not a perfect alternative though, especially if you throw 'from x import *' at it there will probably be some issues, but to have memory of variables and functions it'll work just ok!


Could you provide the content of ~/.cache/sniprun/sniprun.log after one `:SnipRun` command ?

**Comment by peach-lasagna** [comment]
i tried to run with Python3_original . no effect.
I did not find any logs in ~ / .locals / nvim /, nor in ~ / .vim /, nor in ~ / .config / nvim /

**Comment by michaelb** [comment]
What do you mean, no effect? 

The Python3_original interpreter (default) has no quirk, and should work with every distribution out there that has python.
REPL mode is only one config key + 'pip install --user klepto' away

Just me being curious, but do sniprun works with other languages (bash, C) ?


the log should be in `~/.cache/sniprun/sniprun.log`, if nothing is there that's the sign of an underlying issue.
I am very interested in the existence ,and if so, the content of `~/.cache/sniprun/sniprun.log` , as well as the output of `:checkhealth sniprun`, and details on your platform (distro, architecture <- `uname -a` from the terminal?)

**Comment by michaelb** [comment]
in the light of all i said above, your issue might be fixed by reinstalling sniprun with instructions to recompile sniprun locally (see the installation section in the README)

**Comment by peach-lasagna** [comment]
checkheal:
![изображение](https://user-images.githubusercontent.com/59787538/115021350-0fd1b380-9ee6-11eb-94fd-d119e0eb4838.png)
~/.cache directory:
![изображение](https://user-images.githubusercontent.com/59787538/115021993-f0875600-9ee6-11eb-89e7-aa7b34556b16.png)
uname -a:
![изображение](https://user-images.githubusercontent.com/59787538/115022151-30e6d400-9ee7-11eb-897c-42031b135d52.png)

**Comment by peach-lasagna** [comment]
hmm, doesn't work with C either. I definitely didn't install sniprun correctly.
I tried running install.sh. Nothing changed.

**Comment by michaelb** [comment]
okay, thanks.

./install.sh actually tries to download a up-to-date precompiled binary first, and only if it fails, will try to compile locally. Nothing new has happened because the binary is up-to-date, though it is not compatible (for some reason??) with your WSL instance.

However, if given an argument, for example `./install.sh 1` (works also if invoked from the plugin manager as post-install script), it will force a local compilation. You have the rust toolchain available, so there won't be any issue I think, it will be equivalent to run `cargo build --release` btw.

**Comment by michaelb** [comment]
This is somehow interesting though. 

I'll try to add a health check and a message if the binary doesn't work for some reason in the next release

**Comment by peach-lasagna** [comment]
Thank you! `./install.sh 1` helped me
