### ISSUE TITLE
Python - RuntimeError: ModuleNotFoundError: No module named 'klepto'

### ISSUE THREAD

**Issue by yingzhu146** [michaelb/sniprun#66]
**Describe the bug**

RunTimeError when using the Python_original interpreter 
<img width="870" alt="image" src="https://user-images.githubusercontent.com/59233975/115969515-45d8ee00-a50b-11eb-8a3f-a0e58a0fc0ec.png">

```vim
lua << EOF
require'sniprun'.setup({
  selected_interpreters = {},     --" use those instead of the default for the current filetype
  repl_enable = {},               --" enable REPL-like behavior for the given interpreters
  repl_enable = {'Python3_original'},
  repl_disable = {},              --" disable REPL-like behavior for the given interpreters

  inline_messages = 0,             --" inline_message (0/1) is a one-line way to display messages
                                  --" to workaround sniprun not being able to display anything

  -- " you can combo different display modes as desired
  display = {
    -- "Classic",                    -- "display results in the command-line  area
    "VirtualTextOk",              -- "display ok results as virtual text (multiline is shortened)
    "VirtualTextErr",          -- "display error results as virtual text
    "TempFloatingWindow",      -- "display results in a floating window
    --LongTempFloatingWindow",  -- "same as above, but only long results. To use with VirtualText__
    -- "Terminal"                 -- "display results in a vertical split
    },

})
EOF
```

And my `SnipInfo`

```
-n Version :  v0.5.3
 (up-to-date)


Currently selected interpreter: Python3_original, at support level: Import
```

mode of install
```vim
Plug 'michaelb/sniprun', {'do': 'bash install.sh 1'}
```

```vim
:checkhealth
## Installation
  - OK: `tree-sitter` found  0.19.4 (89e1157a299596f3ce2155ba9fd69d5e2c03d3e6) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: Rust toolchain found
  - OK: sniprun binary found
  - ERROR: sniprun binary incompatible or crash at start
    - ADVICE:
      - Compile sniprun locally, with a clean reinstall and 'bash ./install.sh 1' as post-install command.
```
(Note I recompiled multiple times)
 
```bash
❯ file ./target/release/sniprun
./target/release/sniprun: Mach-O 64-bit executable arm64
```

lua appears to work well 

<img width="516" alt="image" src="https://user-images.githubusercontent.com/59233975/115970012-d44e6f00-a50d-11eb-9527-0a4424ca7be5.png">

**What do the bug concerns? Sniprun itself, a particular interpreter?**
The bug seems to stem from the Python interpreter

**Environment:**
```
❯ nvim --version
NVIM v0.5.0-dev+1025-g0fad952a2
Build type: Debug
LuaJIT 2.1.0-beta3
```

**Additional context**

**Comment by michaelb** [comment]
Yep, nothing anormal.

`:SnipInfo Python3_original` should tell you every detail there is to know (a lot, for this particular interpreter)

**Comment by michaelb** [comment]
I'm a bit concerned about the fact that the checkhealth says the sniprun binary crash at start while obviously it's working, but well I have little means to test that

**Comment by michaelb** [comment]
Yet another note: If you plan to use sniprun for Lua/nvim developement, I suggest you try off the Lua_nvim interpreter

**Comment by yingzhu146** [comment]
Hm apologies If I'm being slow - what's wrong about the setup?

```
To get the REPL behaviour (inactive by default) working, you need to isntall the klepto python package: `pip install --user klepto`  
```
-> done that, see the command execution confirming klepto being installed
```
Then, to enable the REPL behavior for python in your config file
`
lua << EOF
require'sniprun'.setup({
  repl_enable = {'Python3_original'}
})
EOF`
```
Done that too (see config)

**Comment by michaelb** [comment]
Oh, sorry, I did miss that part about klepto being installed.

Let's see.... 

What is the default python version for `python` on Mac? (`python --version`)
Python3_original is a python3 interpreter, and there is a possibility python on Mac default to python2 for some reason, which in turns could mean klepto got installed as a python2 package.

How does that sound ?

**Comment by yingzhu146** [comment]
> Yet another note: If you plan to use sniprun for Lua/nvim developement, I suggest you try off the Lua_nvim interpreter

Awesome! how do I achieve this? I've tried:
```
lua << EOF
require'sniprun'.setup({
  selected_interpreters = {'Lua_nvim',},     --" use those instead of the default for the current filetype

})
EOF
```
But `:SnipInfo` 
```
Currently selected interpreter: Lua_original, at support level: Bloc
```

> What is the default python version for `python` on Mac? (`python --version`)
> Python3_original is a python3 interpreter, and there is a possibility python on Mac default to python2 for some reason, which in turns could mean klepto got installed as a python2 package.

Yeah I checked that, I'm not using the default python interpreter (I overwrote it in my $PATH):
```
:! which python    
[No write since last change]
/Users/yingzhu/miniconda3/envs/python38/bin/python
:! python -m pip list | grep klepto 
[No write since last change]
klepto                        0.2.0
:! python --version                 
[No write since last change]
Python 3.8.6
```

**Comment by michaelb** [comment]
Ok, I'm a bit out of ideas; 

If you just run `python3` in your terminal, are you able to `import klepto` ?

This might be not spot-on, but I noticed several irregularities in your config, and probably too much to be just copy/paste typos, even if most have little consequences.
FYI, you should not:
- define twice a key in a lua table 
```
repl_enable = {},               --" enable REPL-like behavior for the given interpreters
repl_enable = {'Python3_original'},
```
- put a comma ',' after a single element on in a table
- define mutliple times the config: i don't know if you're doing that but each one will overwrite the precedent, which would explain some of the behavior observed


Could you try to paste this exact configuration? I'm able to get SnipInfo to display Lua_nvim and to get python3_original + REPL working
```
require'sniprun'.setup({
  repl_enable = {'Python3_original'},
  selected_interpreters = {'Lua_nvim'},

  display = {
    "VirtualTextOk",
    "VirtualTextErr",
    "TempFloatingWindow"
  },
})
```


I also noticed that the Lua_nvim interpreter will not play nice with the new display mode, (because it's a very special one), this might not be possible to fix.

**Comment by yingzhu146** [comment]
> Ok, I'm a bit out of ideas;
> 
> If you just run `python3` in your terminal, are you able to `import klepto` ?

from within vim

```
:!python3 -c "import klepto;print(klepto.__version__)"
0.2.0
:!python -c "import klepto;print(klepto.__version__)" 
0.2.0
```

terminal
```
❯ python -c "import klepto;print(klepto.__version__)"
0.2.0
❯ python3 -c "import klepto;print(klepto.__version__)"
0.2.0
```

> This might be not spot-on, but I noticed several irregularities in your config, and probably too much to be just copy/paste typos, even if most have little consequences.
> FYI, you should not:
> 
> * define twice a key in a lua table
> 
> ```
> repl_enable = {},               --" enable REPL-like behavior for the given interpreters
> repl_enable = {'Python3_original'},
> ```
> 
> * put a comma ',' after a single element in a table ` {'Lua_nvim',},`
Yeah this was just me being careless with copy pasting and too lazy to fix since shouldn't affect anything

> * define mutliple times the config: i don't know if you're doing that but each one will overwrite the precedent, which would explain some of the behavior observed

Yeah it's only defined once

> Could you try to paste and use only this exact configuration? I'm able to get SnipInfo to display Lua_nvim and to get python3_original + REPL working
> 
> ```
> require'sniprun'.setup({
>   repl_enable = {'Python3_original'},
>   selected_interpreters = {'Lua_nvim'},
> 
>   display = {
>     "VirtualTextOk",
>     "VirtualTextErr",
>     "TempFloatingWindow"
>   },
> })
> ```
Done - error persists unfortunately

**Comment by michaelb** [comment]
That's the right package, I have the same, one and only klepto 0.2.0 package.

I'm really at a loss (insert sweating smiley)

**Comment by michaelb** [comment]
I wonder if something could have to do with some PATH issues, but I'm no expert here:

My own pip-installed packages go to '/home/michael/.local/lib/python3.9/site-packages', and not some 'miniconda environment' as I can guess from your path. I'm on linux though so that difference may actually be normal.

It's actually intricated, but maybe the klepto import part of a python script (called by a Rust process spawned by a Lua itself spawned by neovim) has not access to the same environment as you do ? 

I wonder if installing klepto globally will fix the issue (may need root permissions, I think `sudo pip install klepto` will try to install system-wide first  - and succeed since it has the permissions)

**Comment by yingzhu146** [comment]
Ok found it :) As expected it was some PATH issue. However, it was a homebrew installed version, which, somehow, has precedence in whatever execution context the python interpreter is executed. I can't exactly reproduce it ironically but installing it in the homebrew provided version solved it - or uninstalling the homebrew version (which lives in `/opt/homebrew/bin/python3` under ARM)

In a broader sense though - specifying the interpreter/environment would be very important for python/data science heavy workflows. I've went ahead and opened #69 for that.

Thanks a ton for thinking through everything, this can be closed
