### ISSUE TITLE
Feature Request: Support specifying interpreter paths and support python environments

### ISSUE THREAD

**Issue by yingzhu146** [michaelb/sniprun#69]
**Is your feature request related to a problem? Please describe.**
This is coming out of #66 - Pythonistas will often switch between environments. Indeed, I even sometimes have to python REPLs open from different environments. 

**Describe the solution you'd like**
Specify the interpreter a) globally and b) on a per session basis (like Jupyter)

**Comment by yingzhu146** [comment]
I guess we could consider #68 do be quite related/same issue

**Comment by michaelb** [comment]
For #68 , i'll add the option to configure a specific command (python3, python2, gcc, or clang, or even /home/user/custominterpreter etc...)

If there are different things to take into account for python environnements (assume I know next to nothing) could you elaborate ?

**Comment by yingzhu146** [comment]
i think specifying the python path should be enough

**Comment by michaelb** [comment]
i've tried some things already, mostly working :-)

Actually, activating a whole environnment from the shell made this work out of the box.

In dev (and the future 0.5.4 release) one or more venv location will be configurable, and load a venv on demand

**Comment by michaelb** [comment]
0.5.4 was forced a bit early, but it should provide decent functionnality.

See :SnipInfo Python3_original , unfortunately, adapting this to the python3_jupyter may be much harder, but who knows? But there's this emergency fix that can't be delayed, so might as well provide the solution for this issue

**Comment by yingzhu146** [comment]
Hey - I haven't used this plugin in a while since I unfortunately never got this to work and just gave up and used a separate kitty terminal with `vim-slime` instead.

I gave it another try since live mode is one thing I've always dreamt about. And this led me to realize that I still can't get the path to be picked up correctly.

As you can see below I'm using conda (or more specifically mamba) as my environment provider

From `SnipInfo`:
```
-n Version :  v1.2.2
 (up-to-date)


Currently selected interpreter: Python3_original, at support level: Selected
```
my config
```lua
require'sniprun'.setup({
--  selected_interpreters = {'Lua_nvim', 
selected_interpreters = {'Python3_original'},
  interpreter_options = {
    Python3_original = {
        intepreter = "/Users/yingzhu/mambaforge/bin/python",
        }
    },
  live_mode_toggle='enable',
  display = {
    "TempFloatingWindow"
  },

})
```

Am I misunderstanding the syntax? Also it's really hard to debug - would be great if SnipInfo could add some more info (e.g. path of selected interpreter)

**Comment by michaelb** [comment]
> Am I misunderstanding the syntax? 

No, the config looks good



> /Users/yingzhu/mambaforge/bin/python

Is that really the path to a python executable ?


> Also it's really hard to debug 

There is a ~/.cache/sniprun/sniprun.log file that, IIRC, should contain much more information including the interpreter detected/used, copy-pasted log traces. Remote plugins such as sniprun are out-of-process and traditionally 'harder' to debug

**Comment by gerritvreeman** [comment]
@yingzhu146 I think the issue might just be spelling in the config: `intepreter` -> `interpreter` in line 5. I made the same mistake and after fixing it works perfectly.

**Comment by michaelb** [comment]
Whoops, there is indeed a typo in the example !!

Will fix this :-)
