### ISSUE TITLE
C++ namespace definitions cause Compile Error

### ISSUE THREAD

**Issue by danngreen** [michaelb/sniprun#71]
The following C++ code will cause a Compile Error when run with SnipRun, whether the entire file is passed to SnipRun, or if just the line `std::cout << "test";` is selected and run with `:'<,'>SnipRun`
```
namespace MyApplication
{
void foo()
{
std::cout << "test";
}
}
```

If `namespace MyApplication` is commented out, SnipRun works fine.

I'm very excited to use SnipRun, this project looks great! But most of my c++ code uses namespaces (which seems to be a common/recommended practice for modern c++, especially for libraries). I could probably run SnipRun cpp at the Bloc level, but then I'd miss out on the benefits of Import level.

It looks like `fetch_imports` in Cpp_original.rs will grab any line starting with `namespace` and prepend that to the temp file that's compiled, so the generated file (when used just on the single line) is:
```
#include <iostream>
namespace MyApplication
int main() {
std::cout << "test";
return 0;
}
```
which isn't valid C++ code.

I'm wondering why namespaces are included in fetch_import() to begin with. Is it to support things like
`namespace someAliasNs = someOtherNs;`
?

If so, changing this line in Cpp_original.rs
```
if line.starts_with("namespace")
```
to
```
if (line.starts_with("namespace") && line.contains("="))
```

fixes at least the example above (though I might be breaking something else, I'm not sure of the original intention).
Thanks!

**Comment by michaelb** [comment]
You're 100% right with this analysis, I just did not have in mind all the different manners to define namespaces in C++ (only looked up the first SO query match)

If you wish to, you can submit a pull request, I mean you basically found and fixed that yourself, and if you don't I'll fix this sooner rather than later.

However, I also need to support cases where things like

```
using namespace std;

int main(){
     cout << "hello";
}
```

Which should be valid code... 

I'm basically ignorant of any common C++ practice, could you list the cases you can think of that need to be considered/evicted

**Comment by danngreen** [comment]
Yes, `using namespace std;` should be supported, I think it works already.
Also what's known as namespace aliasing, which is `namespace SomeAlias =  SomeNamespace;` could be supported as well (I think). Though, there are some cases where this might not work,  if the file uses different namespace aliases in different scopes -- if SnipRun picks up all the namespace aliases it could be a problem. That said, typically these namespace aliases will be on lines that start with whitespace because they'll be within an enclosing function, class, or namespace, and I believe SnipRun will ignore those.
There is also the use of `inline namespace` which could probably be treated like non-inline version.

I think in general the use of namespace declarations like my example code in the first post should be ignored, but namespace aliases and `using` clauses should be included in imports. It won't work with 100% of code, but will work with more than it does now.

The `using` keyword also is used for typename aliases. Ideally that would be included in imports as well (as it will now), but I'm not sure if there are cases where it'll cause issues.

 I'll write a few tests for these use-cases and submit a pull request.

**Comment by michaelb** [comment]
#72 fixed this
