### ISSUE TITLE
Sniprun says no such file or directory

### ISSUE THREAD

**Issue by the-noob-coder69** [michaelb/sniprun#87]
**Describe the bug**
I don't know what's happening but i am getting an error saying that there is no file or directory `/home/shantnu/.local/share/nvim/sit
e/pack/packer/start/sniprun/target/release/sniprun` even after i did ./install.sh manually (i forgot to add that line in my plugin manager)

**Expected behavior**
It should have run properly without any errors

**Screenshots**
![wth](https://user-images.githubusercontent.com/76793870/126547477-fb2cc69d-400a-4ea6-b7e9-ea217cf34e30.png)

**Environment:**
 - Neovim v0.6.0-dev

**Comment by michaelb** [comment]
To quickly explain what's happening:
Sniprun needs a compiled binary to run, and this is the place where it's supposed to be. The lua part that gets the :SnipRun command has to run (or connect) to that binary, and thus fails if it can't find it.
The install.sh script is in charge of either downloading the binary from github releases, or to compile it locally. If you want to compile locally and have Rust installed, it's equivalent to run `cargo build --release` from sniprun's root directory

Are you really on 0.6 or it is a typo? I may be getting old, but 0.5 stable was release like 2 weeks ago wasn't it? It's quite funny imo (but irrelevant for your issue)

Does :checkhealth sniprun (from neovim) display anything relevant? 
Did ./install.sh succeed and could you check if the binary is present at the given path? What was the output of the script ?

**Comment by the-noob-coder69** [comment]
Ooh, it's working after i compiled with `cargo build --release`. Now can i delete cargo?

> Are you really on 0.6 or it is a typo? I may be getting old, but 0.5 stable was release like 2 weeks ago wasn't it?

yes i am on 0.6.0-dev that's not a typo i was not getting 0.5 on apt so i am still using unstable neovim maybe i will try to install stable version again. 

> Does :checkhealth sniprun (from neovim) display anything relevant?

No in checkhealth it also gives the same error that there's no file or directory called sniprun

> Did ./install.sh succeed and could you check if the binary is present at the given path? What was the output of the script ?

Yes the file you see there in output of ls that was produced by install.sh

**Comment by michaelb** [comment]
Hmm, okay... 
So maybe, for some reason the binary (produced by github actions) that ./install.sh downloads doesn't work on your system (very old or very recent, not Linux, or anything special?). The error message is confusing though.


That means you'll have to continue compiling sniprun locally, with `cargo build --release` as post-install script if you want to get futures updates. There won't be anything major very soon, I have a lot of research to do for the next features.

If you want to uninstall cargo and the Rust toolchain, it'd be better to pin sniprun to the current tag in packer, so a future update won't break it by downloading a non-working binary

**Comment by michaelb** [comment]
it looks like your issue has been resolved, and it's been 4 days since the last update. Closing this now :-)

**Comment by the-noob-coder69** [comment]
Oh sorry i had forgotten about this 😅. And thanks alot for your help
