### ISSUE TITLE
Run functions without print

### ISSUE THREAD

**Issue by saxocellphone** [michaelb/sniprun#90]
Hi, thanks for the great project! I just have a quick suggestion, or maybe it's already here and I'm missing something in the docs. 

From the demos and docs, I see that the result only gets captured from stdout or stderr. I was wondering if it's possible to run the code simply by capturing the return value.

For example, we can run a function like this:
```python
def add(a, b):
    return a + b
```
using a command like `SnipRunFunc 3 4`, which will yield display
```python
def add(a, b):
    return a + b   <- returns: 7
```
If the function has additional outputs, something like this could work
```python
def add(a, b):
    print("HI")
    return a + b  <- "HI" returns: 7
```

This way, we don't have to add print commands anywhere.

**Comment by michaelb** [comment]
Hi!

There is indeed no such feature, but alas, this does not looks to be really feasible for non-trivial cases (dynamic language, simple arg types...)

I don't think I will (can) implement what you want.... And moreover I strive to keep sniprun as predictable and simple as possible

What I can do, however, are print-helpers, maybe adding a print(variable) if a
`variable = 4810 + b;`
is on the last line.

Does that sound good enough?

**Comment by saxocellphone** [comment]
Yep that sounds good. I didn't really think it through all that much, but the points you brought up indeed sounds quite infeasible.
