### ISSUE TITLE
Using sniprun as an API

### ISSUE THREAD

**Issue by jonathf** [michaelb/sniprun#91]
**Is your feature request related to a problem? Please describe.**

I am currently developing an extension that grabs code snippet from markup languages (like markdown, rst, neorg, orgmode), and I was looking into good methods to execute the code (in addition other features like save to disk through tangle).

I could make something myself, by see that sniprun is clearly superior to anything I could make.
Unfortunatly, using sniprun as a library for this purpose seem to be a bit difficult, as it is clearly meant to be a user tool.

**Describe the solution you'd like**

I'd like a more flexible entrypoint in the code. For example expand the `notify` function to have the signature:
```lua
require"sniprun".notify("run", start, end_, filetype, {display = "rpc"})
```
With:
* `filetype` -- the filetype to assume, nil/"" means get type from buffer
* `display = "rpc"` -- allow for the result to be fetched through an interface that uses rpcrequest (using e.g. buffer number as identifier).

**Describe alternatives you've considered**

An even more flexible design would be to allow passing arbitrary strings, like:
```lua
local stdout = require"sniprun".api_run(string_of_code, filetype)
```
But that would require a blocking design.

**Comment by michaelb** [comment]
Hi!

I'm very happy you take interest into sniprun :-)
What you're asking for may be, depending on the details a complete rework or just a small change. 
Here are my two cents:

- a Rust crate/API ? Would allow for blocking design, may be simple to do but hard to use. (You'll need to link into Rust from whatever language you're using). It'll also be more general (usable outside neovim), so bonus pointsfor that.

- a Lua async API ? Doable actually, even though sniprun will stay quite integrated with neovim. I can implement a new display type like you suggested, one that doesn't display anything but instead send back a RPC message to some listener.

- a Lua blocking API (beyond doing it the async way + wait till message come back)...? 😬 Might be beyond my competences, and require too much work


Things like taking a string as input are easy peasy details imo, but consider that any features depending on Import level or above will be out of reach.

I'll tackle this as soon as I get some free time,  I'll probably be able to do something, but if you have any ideas or anything that might help, please share your thoughts

**Comment by jonathf** [comment]
I think a non-blocking design is preferrable. It is just nicer.
And since I am making a neovim extension as well, my preferrance goes to a Lua async API.

I think that if we in the short term can do the simple thing of just having optional filetype as input. I believe I can make sniprun work with that. And after I've made my extension, we can have another look at what is a good idea or not.

Sounds good?

**Comment by michaelb** [comment]
You can try out a WIP of a future api on the dev branch :-)

```
Plug 'michaelb/sniprun', {'branch':'dev', 'do': './install.sh 1'}
```

**Comment by jonathf** [comment]
Cool, I'll take a look.

**Comment by jonathf** [comment]
I don't seem to be able to get Sniprun to work with the dev branch, not the new api command nor the original SnipRun command. The latter works fine when switching back to master though.

Here is my setup with Python:
```lua
    require'sniprun'.setup({
      selected_interpreters = { 'Python3_fifo' },
      repl_enable = {'Python3_fifo'},
      interpreter_options = {},
      display = {"VirtualTextOk", "LongTempFloatingWindow"},
    })
```

Any suggestions as what is going on?

**Comment by michaelb** [comment]
Forgot to mention, the Rust toolchain is needed to build the binary on the dev branch. I only provide binaries for stables releases, so individual commits have to be compiled by the user. (You may need to remove & add back sniprun in your plugin manager)

`:checkheatlh sniprun` should tell you the same thing and maybe more

**Comment by jonathf** [comment]
Sorry, this week suddenly got very busy at work so my hobby project time has all but disapear.
Glad to hear that the feature is stable, and the problem for me was just the lack of compiling the binary. I dobt that would be a problem from my end.

I'm going to take another look, when I have more time again. :)

**Comment by michaelb** [comment]
No worries, there's no deadline

**Comment by michaelb** [comment]
Hi, any news? 

I'm readying to release 5.10, so any changes to the current API will have to wait for the next (5.11) release unless you have last-minutes suggestions :-)

**Comment by jonathf** [comment]
I appologies for the silence. I work in projects that take all of my time in periods. Right now it is particular hectic, and I hae no time for hobby projects.
I have looked at the new API part of the code and it looks great. I just haven't tried it out yet.

**Comment by michaelb** [comment]
Sure, 5.10 is nothing more than a version. If you don't have the timenow, any feedback will be integrated into the next one as I said, this was nothing more than a notice

Take care :-)

I'll be closing this issue at some point, but feel free to link or reopen if you'd like to discuss related enhancements
