### ISSUE TITLE
Support for SageMath

### ISSUE THREAD

**Issue by petRUShka** [michaelb/sniprun#92]
**Describe the language you want support for (compiler, specificities)**
I'd like an interpreter for SageMath that uses SageMath REPL (which is essentially iPython with Sage additions) and that work with detected filetype ".sage" (which is supported by [vim-sage](https://github.com/petRUShka/vim-sage)).

[SageMath](https://www.sagemath.org/) is a quite popular opensource computer-algebra system. Sage code is basically Python code with some [minor additions](http://doc.sagemath.org/html/en/developer/coding_in_python.html#sage-preparsing) ([explaining preparsing](https://doc.sagemath.org/html/en/reference/repl/sage/repl/preparse.html)) and it is preparsing to Python.

**Support Level to achieve**
Having same level of support (Import +REPL**) as Python has would be great!

**Additional context**
Similar project vimcmdline has [SageMath support](https://github.com/jalvesaq/vimcmdline/blob/master/ftplugin/sage_cmdline.vim).

One either run Sage code in Sage REPL (alternative: Sage Notebook) or run .sage file in command line: `sage my_file.sage`. During run of `.sage` file Sage runs [preparsing](https://doc.sagemath.org/html/en/developer/coding_in_python.html#sage-preparsing). Something like `sage -preparse myclass_test.sage`

In Sage code you are able to:
1. import standard python modules
2. import sage modules in special manner
3. use [`load`](https://doc.sagemath.org/html/en/tutorial/programming.html) ([`load` command specificaton](https://doc.sagemath.org/html/en/reference/repl/sage/repl/load.html)), special instruction for load sage file.

Last one is the most popular.

**Comment by michaelb** [comment]
Sagemath looks cool !

I'll have a go on it (but I'm currently on holidays), but know that REPL support is sometimes a bit.... flaky.

Some interpreters (even python's) have poor support for interoperability, so the functionality may or may not be doable.


Do you have any good ressources for interpreter usage and import syntax (beyond the man page, and what i'd find on google' 1st page of results)? If the documentation is cristal clear i'll be able to figure it out, but i haven't taken a look at it yet.

**Comment by petRUShka** [comment]
I've tried to add links in a first place. So I believe item 3 (`load` mechanism) documentation is quite comprehensive.

Item 1 (standard python import) is as in python case. One to one (Sage code is actually compiling to python code).
Item 2 isn't covered by documentation (at least I've not founded it yet) but there is a [good discussion](https://ask.sagemath.org/question/33954/can-i-create-a-sage-file-and-import-it-as-a-python-module/) at ask.sagemath.org.

**Comment by petRUShka** [comment]
Your answer is a very good news!

**Comment by michaelb** [comment]
It'll probably stay as-is for the 5.10 release, but feel free to link this issue or reopen in a future feature request
